package com.linagora.tmail.mailet;

import java.io.IOException;
import java.util.Arrays;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Optional;
import java.util.stream.Stream;

import jakarta.inject.Inject;
import jakarta.mail.Address;
import jakarta.mail.Message;
import jakarta.mail.MessagingException;
import jakarta.mail.internet.InternetAddress;
import jakarta.mail.internet.MimeMessage;

import org.apache.james.core.MailAddress;
import org.apache.james.core.MaybeSender;
import org.apache.james.jmap.mime4j.AvoidBinaryBodyBufferingBodyFactory;
import org.apache.james.mime4j.codec.DecodeMonitor;
import org.apache.james.mime4j.message.DefaultMessageBuilder;
import org.apache.james.mime4j.stream.MimeConfig;
import org.apache.james.server.core.MimeMessageInputStream;
import org.apache.james.util.html.HtmlTextExtractor;
import org.apache.james.util.mime.MessageContentExtractor;
import org.apache.mailet.Mail;
import org.apache.mailet.MailetException;
import org.apache.mailet.base.GenericMailet;

import com.github.fge.lambdas.Throwing;
import com.google.common.base.Strings;

import dev.langchain4j.data.message.ChatMessage;
import dev.langchain4j.data.message.SystemMessage;
import dev.langchain4j.data.message.UserMessage;
import dev.langchain4j.model.chat.ChatLanguageModel;
import dev.langchain4j.model.openai.OpenAiChatModel;

/**
 * OpenAIMailet is a mailet designed to automatically reply to emails
 * sent to a specific recipient (e.g., gpt@linagora.com). It uses the OpenAI
 * API to generate responses.
 *
 * <p>
 * Configuration example:
 *
 * <pre>
 * {@code
 * <mailet match="com.linagora.tmail.mailet.RecipientsContain=gpt@linagora.com" class="com.linagora.tmail.mailet.OpenAIMailet">
 *     <apiKey>demo</apiKey>
 *     <gptAddress>gpt@tmail.com</gptAddress>
 * </mailet>
 * }
 * </pre>
 * </p>
 *
 * <p>
 * The mailet configuration should include the following parameters:
 * </p>
 * <ul>
 * <li><b>apiKey</b>: The API key for accessing the OpenAI service.</li>
 * <li><b>gptAddress</b>: The email address used to send replies generated by the OpenAI model.</li>
 * </ul>
 */
public class OpenAIMailet extends GenericMailet {
    public static final String API_KEY_PARAMETER_NAME = "apiKey";
    public static final String GPT_ADDRESS_PARAMETER_NAME = "gptAddress";

    private final HtmlTextExtractor htmlTextExtractor;

    private ChatLanguageModel openAiModel;
    private MailAddress gptAddress;
    private DefaultMessageBuilder defaultMessageBuilder;

    @Inject
    public OpenAIMailet(HtmlTextExtractor htmlTextExtractor) {
        this.htmlTextExtractor = htmlTextExtractor;
    }

    @Override
    public void service(Mail mail) throws MessagingException {
        if (gptLoopDetected(mail)) {
            return;
        }

        try {
            String gptAnswer = askOpenAiModel(mail);
            MimeMessage replyMimeMessage = evaluateReplyMimeMessage(mail, gptAnswer);

            getMailetContext()
                .sendMail(gptAddress, evaluateRecipients(mail), replyMimeMessage);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    private boolean gptLoopDetected(Mail mail) {
        return mail.getMaybeSender().equals(MaybeSender.of(gptAddress));
    }

    private String askOpenAiModel(Mail mail) throws IOException, MessagingException {
        ChatMessage systemMessage = new SystemMessage("You are a helpful mailing chatbot. Respond to the following email as a chatbot, not as the recipient. ");
        ChatMessage userMessage = new UserMessage(evaluatePrompt(mail));

        return openAiModel.generate(systemMessage, userMessage)
            .content()
            .text();
    }

    private String evaluatePrompt(Mail mail) throws IOException, MessagingException {
        MessageContentExtractor.MessageContent askingMessageContent = extractMessageContent(mail);
        Optional<String> content = askingMessageContent.extractMainTextContent(htmlTextExtractor);

        return Strings.nullToEmpty(mail.getMessage().getSubject()) + "\n" +
            content.orElse("");
    }

    private MessageContentExtractor.MessageContent extractMessageContent(Mail mail) throws IOException, MessagingException {
        return new MessageContentExtractor().extract(defaultMessageBuilder.parseMessage(new MimeMessageInputStream(mail.getMessage())));
    }

    private MimeMessage evaluateReplyMimeMessage(Mail mail, String answer) throws MessagingException {
        MimeMessage reply = (MimeMessage) mail.getMessage()
            .reply(true);

        stripGptFromRecipients(reply, Message.RecipientType.TO);
        stripGptFromRecipients(reply, Message.RecipientType.CC);
        stripGptFromRecipients(reply, Message.RecipientType.BCC);

        reply.setSentDate(new Date());
        reply.setFrom(gptAddress.asString());
        reply.setText(answer);

        return reply;
    }

    private void stripGptFromRecipients(MimeMessage reply, Message.RecipientType recipientType) throws MessagingException {
        Address[] toAddresses = Arrays.stream(Optional.ofNullable(reply.getRecipients(recipientType))
                .orElse(new InternetAddress[0]))
            .filter(Throwing.predicate(address -> !address.equals(new InternetAddress(gptAddress.asString()))))
            .toArray(Address[]::new);
        reply.setRecipients(recipientType, toAddresses);
    }

    private List<MailAddress> evaluateRecipients(Mail mail) {
        return Stream.of(mail.getMaybeSender().asList(), mail.getRecipients())
            .flatMap(Collection::stream)
            .filter(recipient -> !recipient.equals(gptAddress))
            .toList();
    }

    @Override
    public void init() throws MessagingException {
        String openAiApiKey = getMailetConfig().getInitParameter(API_KEY_PARAMETER_NAME);
        if (Strings.isNullOrEmpty(openAiApiKey)) {
            throw new MailetException("No value for " + API_KEY_PARAMETER_NAME + " parameter was provided.");
        }

        String gptAddressString = getMailetConfig().getInitParameter(GPT_ADDRESS_PARAMETER_NAME);
        if (Strings.isNullOrEmpty(gptAddressString)) {
            throw new MailetException("No value for " + GPT_ADDRESS_PARAMETER_NAME + " parameter was provided.");
        }
        gptAddress = new MailAddress(gptAddressString);

        this.openAiModel = OpenAiChatModel.builder()
            .apiKey(openAiApiKey)
            .build();

        this.defaultMessageBuilder = new DefaultMessageBuilder();
        defaultMessageBuilder.setMimeEntityConfig(MimeConfig.PERMISSIVE);
        defaultMessageBuilder.setDecodeMonitor(DecodeMonitor.SILENT);
        defaultMessageBuilder.setBodyFactory(new AvoidBinaryBodyBufferingBodyFactory());
    }

    @Override
    public String getMailetName() {
        return "OpenAIMailet";
    }
}
