= Encrypted mailbox
:navtitle: Encrypted mailbox

See xref:tmail-backend/features/encrypted-mailbox.adoc[this page] for feature explanation.

== Enabling/Disabling the encrypted mailbox

Encrypting messages is costly thus we understand an administrator might choose not to enable this feature.

We provide an easy way to disable completely the **Encrypted Mailbox** through the configuration.

Example: `mailbox.properties`

....
gpg.encryption.enable=false
....

Additionally one need to load the corresponding extension Guice modules in order to use the feature:

....
com.linagora.tmail.james.jmap.method.KeystoreSetMethodModule
com.linagora.tmail.james.jmap.method.KeystoreGetMethodModule
com.linagora.tmail.james.jmap.method.EncryptedEmailDetailedViewGetMethodModule
com.linagora.tmail.james.jmap.method.EncryptedEmailFastViewGetMethodModule

# Choose based on your distribution
com.linagora.tmail.encrypted.cassandra.KeystoreCassandraModule
com.linagora.tmail.encrypted.cassandra.EncryptedEmailContentStoreCassandraModule
com.linagora.tmail.encrypted.KeystoreMemoryModule
com.linagora.tmail.encrypted.InMemoryEncryptedEmailContentStoreModule
com.linagora.tmail.encrypted.postgres.PostgresKeystoreModule
com.linagora.tmail.encrypted.postgres.PostgresEncryptedEmailContentStoreModule
....