= TMail Backend additional configurations
:navtitle: TMail Backend additional configurations

This section presents additional configurations for TMail backend alongside the traditional
xref:james-distributed-app::configure/index.adoc[James Distributed Server configuration].

== Additional Cassandra configurations
Specified to TMail backend, we can configure the following configurations in the *cassandra.properties* file.

.cassandra.properties additional content
|===
| Property name | explanation
| label.change.ttl
| Optional. Duration, default to 60 days. Cassandra Time-to-live for Label change records.
Setting time-to-live to zero means refusing to use time-to-live on label changes.
Example: `label.change.ttl=0 second`.
|===

== Firebase Cloud Messaging configurations

If you wish you to configure pushing notifications via FCM, please configure the `firebase.properties` file.
Omitting the file would mean disable FCM usage.

.firebase.properties
|===
| Property name | explanation
| enable
| Optional. Boolean, default to true. Whether to enable FCM usage.

Example: `enable=true`.

| privatekey.url
| Required if FCM usage is enabled. String. Path to a Service Account key file in JSON format from the Google Developers
Console or a stored user credential using the format supported by the Cloud SDK.
Documentation to generate a private key file for service account: https://firebase.google.com/docs/admin/setup?hl=en#initialize_the_sdk_in_non-google_environments.

Example: `privatekey.url=/root/conf/firebase_push_privatekey.json`.
|===

== Additional Queue configurations
Specified to TMail backend, we can configure the following configurations in the *queue.properties* file.

.queue.properties additional content
|===
| Property name | explanation
| event.bus.keys.choice
| Optional. Default to the RABBITMQ implementation. Supported values (case insensitive): `REDIS` / `RABBITMQ`.

Example: `event.bus.keys.choice=redis` if you want to use Redis for user notifications.
|===

== Additional JMAP configurations
Specified to TMail backend, we can configure the following configurations in the *jmap.properties* file.

.jmap.properties additional content
|===
| Property name | explanation
| public.asset.total.size
| Optional. Configuration maximum size of total public assets that can be uploaded by a user.

Default to 20MB. Supported units are B (bytes) K (KB) M (MB) G (GB).

Example: `public.asset.total.size=20MB`.
|===