= OpenPaas Integration Configurations

Specified to TMail backend, we can configure the following configurations in the *openpaas.properties* file.

For more information about the OpenPaas integration, see xref:tmail-backend/features/openpaas-integration.adoc[OpenPaas Integration].

.openpaas.properties additional content
|===
| Property name | explanation
| rabbitmq.uri
| Optional. URI for RabbitMQ server to communicate with OpenPaas consumer. Example: `rabbitmq.uri=amqp://guest:guest@localhost:5672/`
| openpaas.api.uri
| URI for OpenPaas API. Example: `openpaas.api.uri=http://localhost:8080`
| openpaas.admin.user
| Admin username for OpenPaas. Example: `openpaas.admin.user=admin`
| openpaas.admin.password
| Admin password for OpenPaas. Example: `openpaas.admin.password=admin`
| openpaas.rest.client.trust.all.ssl.certs
| Whether the OpenPaaS Rest client should trust all SSL certificates. Optional, boolean. Default to false.
| openpaas.queues.quorum.bypass
| Whether to ignore quorum queues setting from `rabbitmq.properties`. Optional, boolean. Default to false. If `true`, OpenPaaS queues would use classic queues.
| openpaas.rest.client.response.timeout
| Timeout for OpenPaaS Rest client. Optional. Duration (support multiple time units cf `DurationParser`, default unit is milliseconds), defaults to 30 seconds.
| dav.api.uri
| Optional. URI for DAV API. Example: `dav.api.uri=http://sabre_dav:80/api`
| dav.admin.user
| Admin username for DAV. Example: `dav.admin.user=admin`
| dav.admin.password
| Admin password for DAV. Example: `dav.admin.password=admin`
| dav.rest.client.trust.all.ssl.certs
| Whether the DAV Rest client should trust all SSL certificates. Optional, boolean. Default to false.
| dav.rest.client.response.timeout
| Timeout for DAV Rest client. Optional. Duration (support multiple time units cf `DurationParser`, default unit is milliseconds), defaults to 30 seconds.
|===

== CardDavCollectedContact

This mailet collects contacts from mail recipients and stores them in a CardDAV server using the HTTP API.

=== Example
This configuration sets up in `mailetcontainer.xml`

----
<mailet match="All" class="com.linagora.tmail.mailet.CardDavCollectedContact"/>
----

The docker compose sample for the OpenPaas integration with `CardDavCollectedContact` mailet: see `docker-compose-carddav-sample.yml`.
A sample user `user1@open-paas.org/secret` has been created for testing purposes.

== CalDavCollect

This mailet synchronizes calendars in mails with dav server (create, update, delete calendar events).

=== Parameters

The mailet configuration requires the following parameters:

* `source`: source for this mailet. the value must be same as the value of `destination` attribute in ICALToJsonAttribute mailet.

=== Example
This configuration contains all mailets necessary to read ics attachments in mail and send them to dav server.

[source,xml]
----
<mailet match="All" class="StripAttachment">
    <mimeType>text/calendar</mimeType>
    <attribute>rawIcalendar2</attribute>
    <onMailetException>ignore</onMailetException>
</mailet>
<mailet match="All" class="MimeDecodingMailet">
    <attribute>rawIcalendar2</attribute>
    <onMailetException>ignore</onMailetException>
</mailet>
<mailet match="All" class="ICalendarParser">
    <sourceAttribute>rawIcalendar2</sourceAttribute>
    <destinationAttribute>icalendar2</destinationAttribute>
    <onMailetException>ignore</onMailetException>
</mailet>
<mailet match="All" class="ICALToHeader">
    <attribute>icalendar2</attribute>
    <onMailetException>ignore</onMailetException>
</mailet>
<mailet match="All" class="org.apache.james.transport.mailets.ICALToJsonAttribute">
    <source>icalendar2</source>
    <destination>icalendarAsJson2</destination>
    <rawSource>rawIcalendar2</rawSource>
    <onMailetException>ignore</onMailetException>
</mailet>
<mailet match="All" class="com.linagora.tmail.mailet.CalDavCollect">
    <source>icalendarAsJson2</source>
</mailet>
----