= OpenPaas Integration Configurations

Specified to TMail backend, we can configure the following configurations in the *openpaas.properties* file.

For more information about the OpenPaas integration, see xref:tmail-backend/features/openpaas-integration.adoc[OpenPaas Integration].

.openpaas.properties additional content
|===
| Property name | explanation
| rabbitmq.uri
| Optional. URI for RabbitMQ server to communicate with OpenPaas consumer. Example: `rabbitmq.uri=amqp://guest:guest@localhost:5672/`
| openpaas.api.uri
| URI for OpenPaas API. Example: `openpaas.api.uri=http://localhost:8080`
| openpaas.admin.user
| Admin username for OpenPaas. Example: `openpaas.admin.user=admin`
| openpaas.admin.password
| Admin password for OpenPaas. Example: `openpaas.admin.password=admin`
| openpaas.rest.client.trust.all.ssl.certs
| Whether the OpenPaaS Rest client should trust all SSL certificates. Optional, boolean. Default to false.
| openpaas.queues.quorum.bypass
| Whether to ignore quorum queues setting from `rabbitmq.properties`. Optional, boolean. Default to false. If `true`, OpenPaaS queues would use classic queues.
| carddav.api.uri
| Optional. URI for CardDAV API. Example: `carddav.api.uri=http://sabre_dav:80/api`
| carddav.admin.user
| Admin username for CardDAV. Example: `carddav.admin.user=admin`
| carddav.admin.password
| Admin password for CardDAV. Example: `carddav.admin.password=admin`
| carddav.rest.client.trust.all.ssl.certs
| Whether the CardDAV Rest client should trust all SSL certificates. Optional, boolean. Default to false.
| carddav.rest.client.response.timeout
| Timeout for CardDAV Rest client. Optional, integer. Unit is milliseconds. Default to 10000.
|===

== OpenPaasAmqpForwardAttribute

This mailet forwards the specified mail attribute value to OpenPaas through the AMQP protocol.

=== Parameters

The mailet configuration requires the following parameters:

* `attribute`: the name of the attribute which its value would be forwarded, the value is expected to be a Map<String, byte[]>.
* `exchange`: name of the AMQP exchange.
* `exchange_type`: type of the exchange. Can be "direct", "fanout", "topic", "headers". Optional, defaults to "direct".

=== Example
This configuration forwards contacts extracted by the `ContactExtractor` mailet to OpenPaas through the AMQP protocol.

[source,xml]
----
<mailet match="SenderIsLocal" class="ContactExtractor">
    <attribute>extractedContacts</attribute>
</mailet>

<mailet match="All" class="com.linagora.tmail.mailet.OpenPaasAmqpForwardAttribute">
  <attribute>extractedContacts</attribute>
  <exchange>contacts:contact:add</exchange>
  <exchange_type>FANOUT</exchange_type>
</mailet>
----

== CardDavCollectedContact

This mailet collects contacts from mail recipients and stores them in a CardDAV server using the HTTP API.

=== Example
This configuration sets up in `mailetcontainer.xml`

----
<mailet match="All" class="com.linagora.tmail.mailet.CardDavCollectedContact"/>
----

The docker compose sample for the OpenPaas integration with `CardDavCollectedContact` mailet: see `docker-compose-carddav-sample.yml`.
A sample user `user1@open-paas.org/secret` has been created for testing purposes.