= TMail Backend
:navtitle: TMail backend

TMail backend is the back-bone of TMail, THE **collaborative**, **private and secure** email suite that minimises
**your** impact on the planet.

TMail backend server offers an easy way to scale email server. Based on
noSQL solutions, it is intended to be easy to operate for large
deployments, without needing sharding and protocol aware load balancing. This makes TMail easier to operate.

TMail backend server is based on the xref:james-distributed-app::index.adoc[Apache James Distributed server].

Read more about...

* xref:james-distributed-app::objectives.adoc[Objectives and motivation of the Distributed Server]
* xref:james-distributed-app::architecture/index.adoc[Overview of architecture]
* xref:james-distributed-app::configure/index.adoc[Configure the James Distributed Server]
* xref:tmail-backend/configure/index.adoc[TMail Backend additional configurations]
* xref:james-distributed-app::operate/index.adoc[Operation of the Distributed Server]
* xref:james-distributed-app::extending/index.adoc[How to extend the server]

All of this applies to TMail.

In addition, TMail offers some xref:tmail-backend/features/index.adoc[Advanced features].

We also enhanced some existing James xref:tmail-backend/extra-components/index.adoc[components].

Get on board easily with minimal set up using xref:tmail-backend/test.adoc[TMail testing server], relying solely on
in memory datastructures, thus is light and adapted for functional testing on your local laptop.

However, more advanced users will for sure want to install the xref:tmail-backend/run.adoc[TMail distributed topology].