= TMail: Additional WebAdmin routes
:navtitle: Additional WebAdmin routes

The following document discusses additional webAdmin routes exposed by TMail.

It follows the conventions of xref:3.7.0@james-distributed-app:operate/webadmin.adoc[existing routes for the Apache James
Distributed Server].

== Team Mailboxes

=== Listing Team Mailboxes for a domain

....
curl -XGET http://ip:port/domains/domain.tld/team-mailboxes
....

Returns the list of Team Mailboxes for a given domain:

....
[
  {
     "name": "marketing",
     "emailAddress": "marketing@domain.tld"
  },
...
]
....

Return codes:

 - `400` Invalid domain
 - `404` Domain not found

=== Creating a Team Mailbox

....
curl -XPUT http://ip:port/domains/domain.tld/team-mailboxes/marketting
....

Allows to create a team mailbox.

Return codes:

 - `204` the team mailbox now exists (existed before or was created)
 - `400` invalid alias or name
 - `404` the domain was not found
 - `409` the team mailbox uses an email address used by another entity (user, group, or an alias)

=== Deleting a Team Mailbox

....
curl -XDELETE http://ip:port/domains/domain.tld/team-mailboxes/marketting
....

Allows to delete a team mailbox.

Return codes:

- `204` the team mailbox now no longer exists (did not exist prior the call or was effectively deleted)
- `400` invalid alias or name
- `404` the domain was not found

=== Listing members of a Team Mailbox

....
curl -XGET http://ip:port/domains/domain.tld/team-mailboxes/marketting/members
....

Returns the list of members of the `marketing@domain.tld` team mailbox:

....
[
  {
     "username": "bob@domain.tld"
     "role": "member"
  },
...
]
....

Return codes:

- `400` Invalid domain
- `404` Domain not found, or team mailbox not found

=== Adding a member to a Team Mailbox

....
curl -XPUT http://ip:port/domains/domain.tld/team-mailboxes/marketing/members/bob@domain.tld?role=member
....

Allows creating `bob@domain.tld` user as a member of `marketing@domain.tld` team mailbox.

Query paras:

- `role` Optional. Default to `member`. Value is either `manager` or `member`

Return codes:

- `204` the user is now a member of the team mailbox (either was already a member or was added)
- `400` invalid domain, team mailbox name or user name
- `404` the domain was not found, the team mailbox cannot be found

=== Removing a member for a Team Mailbox

....
curl -XDELETE http://ip:port/domains/domain.tld/team-mailboxes/marketing/members/bob@domain.tld
....

Allows deleting `bob@domain.tld` user as a member of `marketing@domain.tld` team mailbox.

Return codes:

- `204` the user is now is no longer a member of the team mailbox (either was not a member or was effectively removed)
- `400` invalid domain, team mailbox name or user name
- `404` the domain was not found, the team mailbox cannot be found

=== Listing the TeamMailboxes a user have access to

....
curl -XPUT http://ip:port/users/bob@domain.tld/team-mailboxes
....

Returns the list of Team Mailboxes `bob@domain.tld` user has access to :

....
[
  {
     "name": "marketing",
     "emailAddress": "marketing@domain.tld"
  },
...
]
....

Return codes:

- `400` Invalid user
- `404` User not found

== Rate limiting

=== Update rate limits of a user

Allows to update the rate limits bound to a user.

....
curl -XPUT http://ip:port/users/{username}/ratelimits
 -H "Content-Type: application/json"
 -d '{
    "mailsSentPerMinute": 10,
    "mailsSentPerHours": 100,
    "mailsSentPerDays": 1000,
    "mailsReceivedPerMinute": 20,
    "mailsReceivedPerHours": 200,
    "mailsReceivedPerDays": 2000
}'
....

Note: null values are allowed (means no limit set)

Return codes:

- `204` The user rate limits updated successfully
- `400` Invalid request
- `404` User does not exist

=== Get rate limits of a user
....
curl -XGET http://ip:port/users/{username}/ratelimits
....

Returns the limits of a user:

....
{
    "mailsSentPerMinute": 10,
    "mailsSentPerHours": 100,
    "mailsSentPerDays": 1000,
    "mailsReceivedPerMinute": 20,
    "mailsReceivedPerHours": 200,
    "mailsReceivedPerDays": 2000
}
....

Note: Limits not set will return a null value.

Return codes:

- `200` get the rate limits of a user successfully
- `400` Invalid request
- `404` User does not exist

=== Update rate limits of a domain

Allows to update the rate limits bound to a domain.

....
curl -XPUT http://ip:port/domains/{domain}/ratelimits
 -H "Content-Type: application/json"
 -d '{
    "mailsSentPerMinute": 10,
    "mailsSentPerHours": 100,
    "mailsSentPerDays": 1000,
    "mailsReceivedPerMinute": 20,
    "mailsReceivedPerHours": 200,
    "mailsReceivedPerDays": 2000
}'
....

Note: null values are allowed (means no limit set)

Return codes:

- `204` The domain rate limits updated successfully
- `400` Invalid request
- `404` Domain does not exist

=== Get rate limits of a domain
....
curl -XGET http://ip:port/domains/{username}/ratelimits
....

Returns the limits of the domain:

....
{
    "mailsSentPerMinute": 10,
    "mailsSentPerHours": 100,
    "mailsSentPerDays": 1000,
    "mailsReceivedPerMinute": 20,
    "mailsReceivedPerHours": 200,
    "mailsReceivedPerDays": 2000
}
....

Note: Limits not set will return a null value.

Return codes:

- `200` get the rate limits of the domain successfully
- `400` Invalid request
- `404` Domain does not exist

== Domain contacts

=== Create a contact

....
curl -XPOST http://ip:port/domains/{domain}/contacts
{
    "emailAddress": "bob@domain.tld",
    "firstname": "Bob",
    "surname": "Carpenter"
}
....

Creates a new contact attached to a domain

The `firstname` and `surname` fields are optional.

Returns the id of the created contact, as well as a Location header to communicate the URL of the created entry:

....
Location: /domains/domain.tld/contacts/bob
{
    "id": "6b427e04-11de-4674-a4e7-136986d9129e"
}
....

Return codes:

- `201` Contact created successfully
- `400` Invalid domain or mail address, or the domain and the mail address domain don't match
- `404` Domain not found

=== Update a contact

....
curl -XPUT http://ip:port/domains/{domain}/contacts/{username}
{
    "firstname": "Bobby",
    "surname": "Dupond"
}
....

Update the names of a contact. If contact did not exist, it gets created.

The `firstname` and `surname` fields are optional. If a field is omitted, it will not be updated.

Return codes:

- `204` Updated contact successfully
- `400` Invalid domain or mail address
- `404` Domain not found

=== Delete a contact

....
curl -XDELETE http://ip:port/domains/{domain}/contacts/{username}
....

Deletes a contact.

Return codes:

- `204` Deleted contact successfully
- `400` Invalid domain or mail address

=== Get a contact

....
curl -XGET http://ip:port/domains/{domain}/contacts/{username}
....

Return information of that domain contact:

....
{
    "id": "6b427e04-11de-4674-a4e7-136986d9129e",
    "emailAddress": "bob@domain.tld",
    "firstname": "Bob",
    "surname": "Carpenter"
}
....

Return codes:

- `200` Get contact successfully
- `400` Invalid domain or mail address
- `404` Contact not found

=== List all contacts of a domain

....
curl -XGET http://ip:port/domains/{domain}/contacts
....

Returns the list of all contact mail addresses belonging to the domain:

....
["bob@domain.tld", "marie@domain.tld"]
....

Return codes:

- `200` Retrieve the list of contacts successfully
- `400` Invalid domain

=== List all contacts from all domains

....
curl -XGET http://ip:port/domains/contacts/all
....

Returns the list of all contact mail addresses from all domains:

....
["bob@domain.tld", "marie@domain.tld", "andre@otherdomain.tld"]
....

Return codes:

- `200` Retrieve the list of contacts successfully

== Task management


=== Change a username
....
curl -XPOST http://ip:port/users/oldUser/rename/newUser?action=rename
....
Would migrate account data from `oldUser` to `newUser`.
link:https://james.apache.org/server/manage-webadmin.html#Endpoints_returning_a_task[More details about endpoints returning
a task].
Implemented migration steps from James are:

- `ForwardUsernameChangeTaskStep`: creates forward from old user to new user and migrates existing forwards
- `FilterUsernameChangeTaskStep`: migrates users filtering rules
- `DelegationUsernameChangeTaskStep`: migrates delegations where the impacted user is either delegatee or delegator

Implemented extra steps for TMail are:

- `ContactUsernameChangeTaskStep`: migrates contacts from old user to new user
- `PGPKeysUsernameChangeTaskStep`: migrates PGP public keys from old user to new user
- `LabelUsernameChangeTaskStep`: migrates JMAP labels from old to new user
- `JmapSettingsUsernameChangeTaskStep`: migrates JMAP settings from old to new user
- `RateLimitingUsernameChangeTaskStep`: migrates rate limiting from old to new user
- `SaaSAccountUsernameChangeTaskStep` (only if the SaaS module is enabled): migrates SaaS account information from old to new user

Response codes:
* 201: Success. Corresponding task id is returned.
* 400: Error in the request. Details can be found in the reported error.
The `fromStep` query parameter allows skipping previous steps, allowing to resume the username change from a failed step.
The scheduled task will have the following type `UsernameChangeTask` and the following `additionalInformation`:
....
{
        "type": "UsernameChangeTask",
        "oldUser": "jessy.jones@domain.tld",
        "newUser": "jessy.smith@domain.tld",
        "status": {
            "A": "DONE",
            "B": "FAILED",
            "C": "ABORTED"
        },
        "fromStep": null,
        "timestamp": "2023-02-17T02:54:01.246477Z"
}
....
Valid status includes:
- `SKIPPED`: bypassed via `fromStep` setting
- `WAITING`: Awaits execution
- `IN_PROGRESS`: Currently executed
- `FAILED`: Error encountered while executing this step. Check the logs.
- `ABORTED`: Won't be executed because of previous step failures.

=== Delete data of a user

....
curl -XPOST http://ip:port/users/usernameToBeUsed?action=deleteData
....

Would create a task that deletes data of the user.

link:https://james.apache.org/server/manage-webadmin.html#Endpoints_returning_a_task[More details about endpoints returning
a task].

Implemented migration steps from James are:

- `RecipientRewriteTableUserDeletionTaskStep`: deletes all rewriting rules related to this user.
- `FilterUserDeletionTaskStep`: deletes all filters belonging to the user.
- `DelegationUserDeletionTaskStep`: deletes all delegations from / to the user.
- `MailboxUserDeletionTaskStep`: deletes mailboxes of this user, all ACLs of this user, as well as his subscriptions.
- `WebPushUserDeletionTaskStep`: deletes push data registered for this user.
- `IdentityUserDeletionTaskStep`: deletes identities registered for this user.
- `VacationUserDeletionTaskStep`: deletes vacations registered for this user.

Implemented extra steps for TMail are:

- `ContactUserDeletionTaskStep`: deletes contacts belonging to the user.
- `PGPKeysUserDeletionTaskStep`: remove PGP public keys belonging to the user.
- `FirebaseSubscriptionUserDeletionTaskStep`: deletes firebase subscriptions belonging to the user.
- `LabelUserDeletionTaskStep`: deletes JMAP labels belonging to the user.
- `JmapSettingsUserDeletionTaskStep`: deletes JMAP settings belonging to the user.
- `PublicAssetDeletionTaskStep`: deletes public assets belonging to the user.

Response codes:

* 201: Success. Corresponding task id is returned.
* 400: Error in the request. Details can be found in the reported error.

The `fromStep` query parameter allows skipping previous steps, allowing to resume the user data deletion from a failed step.

The scheduled task will have the following type `DeleteUserDataTask` and the following `additionalInformation`:

....
{
        "type": "DeleteUserDataTask",
        "username": "jessy.jones@domain.tld",
        "status": {
            "A": "DONE",
            "B": "FAILED",
            "C": "ABORTED"
        },
        "fromStep": null,
        "timestamp": "2023-02-17T02:54:01.246477Z"
}
....

Valid status includes:

- `SKIPPED`: bypassed via `fromStep` setting
- `WAITING`: Awaits execution
- `IN_PROGRESS`: Currently executed
- `FAILED`: Error encountered while executing this step. Check the logs.
- `ABORTED`: Won't be executed because of previous step failures.

== Mailboxes

=== Clean Trash

....
curl -POST http://ip:port/mailboxes?task=CleanupTrash&usersPerSecond={usersPerSecondValue}
....

Delete all messages in the trash mailbox that are expired

An admin can specify the concurrency that should be used when running the task:

- usersPerSecond rate at which users should be processed, per second. Default to 1.

Return codes:

 - `201` Success. Corresponding task id is returned.
 - `400` Error in the request. Details can be found in the reported error.

=== Clean Spam

....
curl -XPOST http://ip:port/mailboxes?task=CleanupSpam&usersPerSecond={usersPerSecondValue}
....

Delete all messages in the spam mailbox that are expired

An admin can specify the concurrency that should be used when running the task:

- usersPerSecond rate at which users should be processed, per second. Default to 1.

Return codes:

- `201` Success. Corresponding task id is returned.
- `400` Error in the request. Details can be found in the reported error.

=== Inbox archival

The Inbox archival task that allows old messages in users' INBOX to be archived.

....
curl -XPOST http://ip:port/mailboxes?task=InboxArchival
....

Response codes:

* 201: Success. Corresponding task id is returned.
* 400: Error in the request. Details can be found in the reported error.

=== Contact indexing

The Contact Indexing Task facilitates the creation of a contact index for autocomplete functionality. This index is generated by extracting email addresses from messages in the Sent mailbox of a user, in case the index does not already exist.

....
curl -XPOST http://ip:port/mailboxes?task=ContactIndexing&usersPerSecond={usersPerSecondValue}
....

An admin can specify the concurrency that should be used when running the task:

- usersPerSecond rate at which users should be processed, per second. Default to 1.

Response codes:

* 201: Success. Corresponding task id is returned.
* 400: Error in the request. Details can be found in the reported error.

== JMAP OIDC

=== Backchannel logout

If you use OIDC authentication, the Backchannel logout route can be called by your OIDC provider to invalidate OIDC tokens
on TMail backend server when the user logs out of his JMAP client.

....
curl -XPOST http://ip:port/add-revoked-token?logout_token=[LOGOUT_TOKEN]
....

Where the `logout_token` is a JWT token sent by the OIDC provider during backchannel logout mechanism. It should contain
at least the `sid` that TMail will use to invalidate the token stored in cache, so that it can not be used to anymore to
access backend resources.

Response codes:

* 200: Success. Token has been invalidated.
* 400: Error in the request. Details can be found in the reported error.
* 415: Content type is invalid. It must be `application/x-www-form-urlencoded`.

== User quota reports

=== Get count of users having specific quotas

This endpoint returns the total number of users that have a specific quota (different from domain or global default quotas).

....
curl -XGET http://ip:port/reports/quota/users/count?hasSpecificQuota
....

Response example:

....
3
....

Return codes:

- `200` Successfully returned the count
- `400` Missing the `hasSpecificQuota` query parameter

=== List users having specific quotas

Returns the list of users that have specific quotas, along with their specific storage and message count limits.

....
curl -XGET http://ip:port/reports/quota/users?hasSpecificQuota
....

Response example:

....
[
  {
    "user": "bob@domain.tld",
    "storageLimit": 2147483648,
    "countLimit": 10000
  },
  {
    "user": "alice@domain.tld",
    "storageLimit": null,
    "countLimit": 5000
  }
]
....

Return codes:

- `200` Successfully returned the list
- `400` Missing the `hasSpecificQuota` query parameter

=== Get aggregated sum of user extra quotas

Returns aggregated information about user specific quotas, including total extra storage and message count limits compared to their respective domain quotas, as well as how many users have unlimited quotas.

....
curl -XGET http://ip:port/reports/quota/users/sum?hasSpecificQuota
....

Response example:

....
{
    "totalExtraStorageLimit": 3221225472,
    "totalExtraCountLimit": 12000,
    "totalUnlimitedStorage": 1,
    "totalUnlimitedCount": 0
}
....

Return codes:

- `200` Successfully returned the aggregated data
- `400` Missing the `hasSpecificQuota` query parameter
