= TMail: Additional WebAdmin routes
:navtitle: Additional WebAdmin routes

The following document discusses additional webAdmin routes exposed by TMail.

It follows the conventions of xref:3.7.0@james-distributed-app:operate/webadmin.adoc[existing routes for the Apache James
Distributed Server].

== Team Mailboxes

=== Listing Team Mailboxes for a domain

....
curl -XGET http://ip:port/domains/domain.tld/team-mailboxes
....

Returns the list of Team Mailboxes for a given domain:

....
[
  {
     "name": "marketing",
     "emailAddress": "marketing@domain.tld"
  },
...
]
....

Return codes:

 - `400` Invalid domain
 - `404` Domain not found

=== Creating a Team Mailbox

....
curl -XPUT http://ip:port/domains/domain.tld/team-mailboxes/marketting
....

Allows to create a team mailbox.

Return codes:

 - `204` the team mailbox now exists (existed before or was created)
 - `400` invalid alias or name
 - `404` the domain was not found
 - `409` the team mailbox uses an email address used by another entity (user, group, or an alias)

=== Deleting a Team Mailbox

....
curl -XDELETE http://ip:port/domains/domain.tld/team-mailboxes/marketting
....

Allows to delete a team mailbox.

Return codes:

- `204` the team mailbox now no longer exists (did not exist prior the call or was effectively deleted)
- `400` invalid alias or name
- `404` the domain was not found

=== Listing members of a Team Mailbox

....
curl -XGET http://ip:port/domains/domain.tld/team-mailboxes/marketting/members
....

Returns the list of members of the `marketing@domain.tld` team mailbox:

....
[
  {
     "username": "bob@domain.tld"
     "role": "member"
  },
...
]
....

Return codes:

- `400` Invalid domain
- `404` Domain not found, or team mailbox not found

=== Adding a member to a Team Mailbox

....
curl -XPUT http://ip:port/domains/domain.tld/team-mailboxes/marketing/members/bob@domain.tld?role=member
....

Allows creating `bob@domain.tld` user as a member of `marketing@domain.tld` team mailbox.

Query paras:

- `role` Optional. Default to `member`. Value is either `manager` or `member`

Return codes:

- `204` the user is now a member of the team mailbox (either was already a member or was added)
- `400` invalid domain, team mailbox name or user name
- `404` the domain was not found, the team mailbox cannot be found

=== Removing a member for a Team Mailbox

....
curl -XDELETE http://ip:port/domains/domain.tld/team-mailboxes/marketing/members/bob@domain.tld
....

Allows deleting `bob@domain.tld` user as a member of `marketing@domain.tld` team mailbox.

Return codes:

- `204` the user is now is no longer a member of the team mailbox (either was not a member or was effectively removed)
- `400` invalid domain, team mailbox name or user name
- `404` the domain was not found, the team mailbox cannot be found

=== Listing the TeamMailboxes a user have access to

....
curl -XPUT http://ip:port/users/bob@domain.tld/team-mailboxes
....

Returns the list of Team Mailboxes `bob@domain.tld` user has access to :

....
[
  {
     "name": "marketing",
     "emailAddress": "marketing@domain.tld"
  },
...
]
....

Return codes:

- `400` Invalid user
- `404` User not found

== Rate limiting

=== Create a new plan
Allow to create a new rate limiting plan.
....
curl -XPOST http://ip:port/rate-limit-plans/{RateLimitingPlanName}
 -H "Content-Type: application/json"
 -d '{
	"transitLimits": [{
			"name": "receivedMailsPerHour",
			"periodInSeconds": 3600,
			"count": 100,
			"size": 2048
		},
		{
			"name": "receivedMailsPerDay",
			"periodInSeconds": 86400,
			"count": 1000,
			"size": 4096
		}
	],
	"relayLimits": [{
		"name": "relayMailsPerHour",
		"periodInSeconds": 3600,
		"count": 100,
		"size": 2048
	}],
	"deliveryLimits": [{
		"name": "deliveryMailsPerHour",
		"periodInSeconds": 3600,
		"count": 100,
		"size": 2048
	}]
}'
....

Return planId of created plan:
....
{
	"planId": "6b427706-11de-4674-a4e7-166983d9119e"
}
....
Return codes:

- `201` The plan created successfully
- `400` Invalid request

=== Edit a plan

....
curl -XPUT http://ip:port/rate-limit-plans/{RateLimitingPlanId}
 -H "Content-Type: application/json"
 -d '{
    "transitLimits": [
        {
            "name": "receivedMailsPerHour",
            "periodInSeconds": 3600,
            "count": 100,
            "size": 2048
        },
        {
            "name": "receivedMailsPerDay",
            "periodInSeconds": 86400
            "count": 1000,
            "size": 4096
        }
    ],
    "relayLimits": [
        {
            "name": "relayMailsPerHour",
            "periodInSeconds": 3600,
            "count": 100,
            "size": 2048
        }
    ],
    "deliveryLimits": [
        {
            "name": "deliveryMailsPerHour",
            "periodInSeconds": 3600,
            "count": 100,
            "size": 2048
        }
    ]
}'
....

Allow to update an existing plan.

Return codes:

- `204` The plan updated successfully
- `400` Invalid request
- `404` Plan does not exist

=== Get a plan

....
curl -XGET http://ip:port/rate-limit-plans/{RateLimitingPlanId}
....

Return a plan:
....
{
	"planId": "65b94d87-b077-4994-bc82-ab87c4e68313",
	"planName": "oldPlanName",
	"transitLimits": [{
			"name": "receivedMailsPerHour",
			"periodInSeconds": 3600,
			"count": 100,
			"size": 2048
		},
		{
			"name": "receivedMailsPerDay",
			"periodInSeconds": 86400,
			"count": 1000,
			"size": 4096
		}
	],
	"relayLimits": [{
		"name": "relayMailsPerHour",
		"periodInSeconds": 3600,
		"count": 100,
		"size": 2048
	}],
	"deliveryLimits": [{
		"name": "deliveryMailsPerHour",
		"periodInSeconds": 3600,
		"count": 100,
		"size": 2048
	}]
}
....

Return codes:

- `200` Get the plan successfully
- `400` Invalid request
- `404` Plan does not exist

=== Get all plans

....
curl -XGET http://ip:port/rate-limit-plans
....

Return all existing plans:
....
[{
		"planId": "524acec6-7910-4137-b862-7ec1ab048404",
		"planName": "plan1",
		"transitLimits": [{
				"name": "receivedMailsPerHour",
				"periodInSeconds": 3600,
				"count": 100,
				"size": 2048
			},
			{
				"name": "receivedMailsPerDay",
				"periodInSeconds": 86400,
				"count": 1000,
				"size": 4096
			}
		],
		"relayLimits": [{
			"name": "relayMailsPerHour",
			"periodInSeconds": 3600,
			"count": 100,
			"size": 2048
		}],
		"deliveryLimits": [{
			"name": "deliveryMailsPerHour",
			"periodInSeconds": 3600,
			"count": 100,
			"size": 2048
		}]
	},
	{
		"planId": "2fc6b2d7-9b62-42f0-aa8a-5ab62168e0c5",
		"planName": "plan2",
		"transitLimits": [{
				"name": "receivedMailsPerHour",
				"periodInSeconds": 3600,
				"count": 100,
				"size": 2048
			},
			{
				"name": "receivedMailsPerDay",
				"periodInSeconds": 86400,
				"count": 1000,
				"size": 4096
			}
		],
		"relayLimits": [{
			"name": "relayMailsPerHour",
			"periodInSeconds": 3600,
			"count": 100,
			"size": 2048
		}],
		"deliveryLimits": [{
			"name": "deliveryMailsPerHour",
			"periodInSeconds": 3600,
			"count": 100,
			"size": 2048
		}]
	}
]
....

Return codes:

- `200` Get all plans successfully

=== Attach a plan to a user
....
curl -XPUT http://ip:port/users/{username}/rate-limit-plans/{planId}
....

Attach a rate limiting plan to a user. This also can be used to reattach a new plan to that user.

Return codes:

- `204` Attached the plan to the user successfully
- `400` Invalid request
- `404` Either plan or user is not found

=== Get list of users belonging to a plan
....
curl -XGET http://ip:port/rate-limit-plans/{planId}/users
....

Return users belong to a plan:
....
[
    "bob@linagora.com",
    "andre@linagora.com"
]
....

Return codes:

- `200` Get all users belong to that plan successfully
- `400` Invalid request
- `404` Plan is not found

=== Get plan of a user
....
curl -XGET http://ip:port/users/{username}/rate-limit-plans
....

Return rate limiting planId attached to that user:
....
{
    "planId": "02242f08-515c-4170-945e-64afa991f149"
}
....

Return codes:

- `200` Get plan of that user successfully
- `400` Invalid request
- `404` Either user is not found or that user does not have a plan.

=== Revoke plan of a user
....
curl -XDELETE http://ip:port/users/{username}/rate-limit-plans
....

Revoke the plan attached to that user.

Return codes:

- `204` Revoke plan of that user successfully
- `400` Invalid request
- `404` User is not found

== Domain contacts

=== Create a contact

....
curl -XPOST http://ip:port/domains/{domain}/contacts
{
    "emailAddress": "bob@domain.tld",
    "firstname": "Bob",
    "surname": "Carpenter"
}
....

Creates a new contact attached to a domain

The `firstname` and `surname` fields are optional.

Returns the id of the created contact, as well as a Location header to communicate the URL of the created entry:

....
Location: /domains/domain.tld/contacts/bob
{
    "id": "6b427e04-11de-4674-a4e7-136986d9129e"
}
....

Return codes:

- `201` Contact created successfully
- `400` Invalid domain or mail address, or the domain and the mail address domain don't match
- `404` Domain not found

=== Update a contact

....
curl -XPUT http://ip:port/domains/{domain}/contacts/{username}
{
    "firstname": "Bobby",
    "surname": "Dupond"
}
....

Update the names of a contact. If contact did not exist, it gets created.

The `firstname` and `surname` fields are optional. If a field is omitted, it will not be updated.

Return codes:

- `204` Updated contact successfully
- `400` Invalid domain or mail address
- `404` Domain not found

=== Delete a contact

....
curl -XDELETE http://ip:port/domains/{domain}/contacts/{username}
....

Deletes a contact.

Return codes:

- `204` Deleted contact successfully
- `400` Invalid domain or mail address

=== Get a contact

....
curl -XGET http://ip:port/domains/{domain}/contacts/{username}
....

Return information of that domain contact:

....
{
    "id": "6b427e04-11de-4674-a4e7-136986d9129e",
    "emailAddress": "bob@domain.tld",
    "firstname": "Bob",
    "surname": "Carpenter"
}
....

Return codes:

- `200` Get contact successfully
- `400` Invalid domain or mail address
- `404` Contact not found

=== List all contacts of a domain

....
curl -XGET http://ip:port/domains/{domain}/contacts
....

Returns the list of all contact mail addresses belonging to the domain:

....
["bob@domain.tld", "marie@domain.tld"]
....

Return codes:

- `200` Retrieve the list of contacts successfully
- `400` Invalid domain

=== List all contacts from all domains

....
curl -XGET http://ip:port/domains/contacts/all
....

Returns the list of all contact mail addresses from all domains:

....
["bob@domain.tld", "marie@domain.tld", "andre@otherdomain.tld"]
....

Return codes:

- `200` Retrieve the list of contacts successfully

== Task management


=== Change a username
....
curl -XPOST http://ip:port/users/oldUser/rename/newUser?action=rename
....
Would migrate account data from `oldUser` to `newUser`.
link:https://james.apache.org/server/manage-webadmin.html#Endpoints_returning_a_task[More details about endpoints returning
a task].
Implemented migration steps from James are:

- `ForwardUsernameChangeTaskStep`: creates forward from old user to new user and migrates existing forwards
- `FilterUsernameChangeTaskStep`: migrates users filtering rules
- `DelegationUsernameChangeTaskStep`: migrates delegations where the impacted user is either delegatee or delegator

Implemented extra steps for TMail are:

- `ContactUsernameChangeTaskStep`: migrates contacts from old user to new user
- `PGPKeysUsernameChangeTaskStep`: migrates PGP public keys from old user to new user
- `RateLimitingPlanUsernameChangeTaskStep`: migrates rate limiting plan from old to new user
- `LabelUsernameChangeTaskStep`: migrates JMAP labels from old to new user
- `JmapSettingsUsernameChangeTaskStep`: migrates JMAP settings from old to new user

Response codes:
* 201: Success. Corresponding task id is returned.
* 400: Error in the request. Details can be found in the reported error.
The `fromStep` query parameter allows skipping previous steps, allowing to resume the username change from a failed step.
The scheduled task will have the following type `UsernameChangeTask` and the following `additionalInformation`:
....
{
        "type": "UsernameChangeTask",
        "oldUser": "jessy.jones@domain.tld",
        "newUser": "jessy.smith@domain.tld",
        "status": {
            "A": "DONE",
            "B": "FAILED",
            "C": "ABORTED"
        },
        "fromStep": null,
        "timestamp": "2023-02-17T02:54:01.246477Z"
}
....
Valid status includes:
- `SKIPPED`: bypassed via `fromStep` setting
- `WAITING`: Awaits execution
- `IN_PROGRESS`: Currently executed
- `FAILED`: Error encountered while executing this step. Check the logs.
- `ABORTED`: Won't be executed because of previous step failures.

=== Delete data of a user

....
curl -XPOST http://ip:port/users/usernameToBeUsed?action=deleteData
....

Would create a task that deletes data of the user.

link:https://james.apache.org/server/manage-webadmin.html#Endpoints_returning_a_task[More details about endpoints returning
a task].

Implemented migration steps from James are:

- `RecipientRewriteTableUserDeletionTaskStep`: deletes all rewriting rules related to this user.
- `FilterUserDeletionTaskStep`: deletes all filters belonging to the user.
- `DelegationUserDeletionTaskStep`: deletes all delegations from / to the user.
- `MailboxUserDeletionTaskStep`: deletes mailboxes of this user, all ACLs of this user, as well as his subscriptions.
- `WebPushUserDeletionTaskStep`: deletes push data registered for this user.
- `IdentityUserDeletionTaskStep`: deletes identities registered for this user.
- `VacationUserDeletionTaskStep`: deletes vacations registered for this user.

Implemented extra steps for TMail are:

- `ContactUserDeletionTaskStep`: deletes contacts belonging to the user.
- `PGPKeysUserDeletionTaskStep`: remove PGP public keys belonging to the user.
- `FirebaseSubscriptionUserDeletionTaskStep`: deletes firebase subscriptions belonging to the user.
- `LabelUserDeletionTaskStep`: deletes JMAP labels belonging to the user.
- `JmapSettingsUserDeletionTaskStep`: deletes JMAP settings belonging to the user.
- `PublicAssetDeletionTaskStep`: deletes public assets belonging to the user.

Response codes:

* 201: Success. Corresponding task id is returned.
* 400: Error in the request. Details can be found in the reported error.

The `fromStep` query parameter allows skipping previous steps, allowing to resume the user data deletion from a failed step.

The scheduled task will have the following type `DeleteUserDataTask` and the following `additionalInformation`:

....
{
        "type": "DeleteUserDataTask",
        "username": "jessy.jones@domain.tld",
        "status": {
            "A": "DONE",
            "B": "FAILED",
            "C": "ABORTED"
        },
        "fromStep": null,
        "timestamp": "2023-02-17T02:54:01.246477Z"
}
....

Valid status includes:

- `SKIPPED`: bypassed via `fromStep` setting
- `WAITING`: Awaits execution
- `IN_PROGRESS`: Currently executed
- `FAILED`: Error encountered while executing this step. Check the logs.
- `ABORTED`: Won't be executed because of previous step failures.

== Mailboxes

=== Clean Trash

....
curl -POST http://ip:port/mailboxes?task=CleanupTrash&usersPerSecond={usersPerSecondValue}
....

Delete all messages in the trash mailbox that are expired

An admin can specify the concurrency that should be used when running the task:

- usersPerSecond rate at which users should be processed, per second. Default to 1.

Return codes:

 - `201` Success. Corresponding task id is returned.
 - `400` Error in the request. Details can be found in the reported error.

=== Clean Spam

....
curl -XPOST http://ip:port/mailboxes?task=CleanupSpam&usersPerSecond={usersPerSecondValue}
....

Delete all messages in the spam mailbox that are expired

An admin can specify the concurrency that should be used when running the task:

- usersPerSecond rate at which users should be processed, per second. Default to 1.

Return codes:

- `201` Success. Corresponding task id is returned.
- `400` Error in the request. Details can be found in the reported error.

=== Inbox archival

The Inbox archival task that allows old messages in users' INBOX to be archived.

....
curl -XPOST http://ip:port/mailboxes?task=InboxArchival
....

Response codes:

* 201: Success. Corresponding task id is returned.
* 400: Error in the request. Details can be found in the reported error.

=== Contact indexing

The Contact Indexing Task facilitates the creation of a contact index for autocomplete functionality. This index is generated by extracting email addresses from messages in the Sent mailbox of a user, in case the index does not already exist.

....
curl -XPOST http://ip:port/mailboxes?task=ContactIndexing&usersPerSecond={usersPerSecondValue}
....

An admin can specify the concurrency that should be used when running the task:

- usersPerSecond rate at which users should be processed, per second. Default to 1.

Response codes:

* 201: Success. Corresponding task id is returned.
* 400: Error in the request. Details can be found in the reported error.

== JMAP OIDC

=== Backchannel logout

If you use OIDC authentication, the Backchannel logout route can be called by your OIDC provider to invalidate OIDC tokens
on TMail backend server when the user logs out of his JMAP client.

....
curl -XPOST http://ip:port/add-revoked-token?logout_token=[LOGOUT_TOKEN]
....

Where the `logout_token` is a JWT token sent by the OIDC provider during backchannel logout mechanism. It should contain
at least the `sid` that TMail will use to invalidate the token stored in cache, so that it can not be used to anymore to
access backend resources.

Response codes:

* 200: Success. Token has been invalidated.
* 400: Error in the request. Details can be found in the reported error.
* 415: Content type is invalid. It must be `application/x-www-form-urlencoded`.
