= TMail: Additional WebAdmin routes
:navtitle: Additional WebAdmin routes

The following document discusses additional webAdmin routes exposed by TMail.

It follows the conventions of xref:3.7.0@james-distributed-app:operate/webadmin.adoc[existing routes for the Apache James
Distributed Server].

== Team Mailboxes

=== Listing Team Mailboxes for a domain

....
curl -XGET http://ip:port/domains/domain.tld/team-mailboxes
....

Returns the list of Team Mailboxes for a given domain:

....
[
  {
     "name": "marketing",
     "emailAddress": "marketing@domain.tld"
  },
...
]
....

Return codes:

 - `400` Invalid domain
 - `404` Domain not found

=== Creating a Team Mailbox

....
curl -XPUT http://ip:port/domains/domain.tld/team-mailboxes/marketting
....

Allows to create a team mailbox.

Return codes:

 - `204` the team mailbox now exists (existed before or was created)
 - `400` invalid alias or name
 - `404` the domain was not found
 - `409` the team mailbox uses an email address used by another entity (user, group, or an alias)

=== Deleting a Team Mailbox

....
curl -XDELETE http://ip:port/domains/domain.tld/team-mailboxes/marketting
....

Allows to delete a team mailbox.

Return codes:

- `204` the team mailbox now no longer exists (did not exist prior the call or was effectively deleted)
- `400` invalid alias or name
- `404` the domain was not found

=== Listing members of a Team Mailbox

....
curl -XGET http://ip:port/domains/domain.tld/team-mailboxes/marketting/members
....

Returns the list of members of the `marketing@domain.tld` team mailbox:

....
[
  {
     "username": "bob@domain.tld"
  },
...
]
....

Return codes:

- `400` Invalid domain
- `404` Domain not found, or team mailbox not found

=== Adding a member to a Team Mailbox

....
curl -XPUT http://ip:port/domains/domain.tld/team-mailboxes/marketing/bob@domain.tld
....

Allows creating `bob@domain.tld` user as a member of `marketing@domain.tld` team mailbox.

Return codes:

- `204` the user is now a member of the team mailbox (either was already a member or was added)
- `400` invalid domain, team mailbox name or user name
- `404` the domain was not found, the team mailbox cannot be found

=== Removing a member for a Team Mailbox

....
curl -XPUT http://ip:port/domains/domain.tld/team-mailboxes/marketing/bob@domain.tld
....

Allows deleting `bob@domain.tld` user as a member of `marketing@domain.tld` team mailbox.

Return codes:

- `204` the user is now is no longer a member of the team mailbox (either was not a member or was effectively removed)
- `400` invalid domain, team mailbox name or user name
- `404` the domain was not found, the team mailbox cannot be found

=== Listing the TeamMailboxes a user have access to

....
curl -XPUT http://ip:port/users/bob@domain.tld/team-mailboxes
....

Returns the list of Team Mailboxes `bob@domain.tld` user has access to :

....
[
  {
     "name": "marketing",
     "emailAddress": "marketing@domain.tld"
  },
...
]
....

Return codes:

- `400` Invalid user
- `404` User not found

== Rate limiting

=== Create a new plan
Allow to create a new rate limiting plan.
....
curl -XPOST http://ip:port/rate-limit-plans/{RateLimitingPlanName}
 -H "Content-Type: application/json"
 -d '{
	"transitLimits": [{
			"name": "receivedMailsPerHour",
			"periodInSeconds": 3600,
			"count": 100,
			"size": 2048
		},
		{
			"name": "receivedMailsPerDay",
			"periodInSeconds": 86400,
			"count": 1000,
			"size": 4096
		}
	],
	"relayLimits": [{
		"name": "relayMailsPerHour",
		"periodInSeconds": 3600,
		"count": 100,
		"size": 2048
	}],
	"deliveryLimits": [{
		"name": "deliveryMailsPerHour",
		"periodInSeconds": 3600,
		"count": 100,
		"size": 2048
	}]
}'
....

Return planId of created plan:
....
{
	"planId": "6b427706-11de-4674-a4e7-166983d9119e"
}
....
Return codes:

- `201` The plan created successfully
- `400` Invalid request

=== Edit a plan

....
curl -XPUT http://ip:port/rate-limit-plans/{RateLimitingPlanId}
 -H "Content-Type: application/json"
 -d '{
    "transitLimits": [
        {
            "name": "receivedMailsPerHour",
            "periodInSeconds": 3600,
            "count": 100,
            "size": 2048
        },
        {
            "name": "receivedMailsPerDay",
            "periodInSeconds": 86400
            "count": 1000,
            "size": 4096
        }
    ],
    "relayLimits": [
        {
            "name": "relayMailsPerHour",
            "periodInSeconds": 3600,
            "count": 100,
            "size": 2048
        }
    ],
    "deliveryLimits": [
        {
            "name": "deliveryMailsPerHour",
            "periodInSeconds": 3600,
            "count": 100,
            "size": 2048
        }
    ]
}'
....

Allow to update an existing plan.

Return codes:

- `204` The plan updated successfully
- `400` Invalid request
- `404` Plan does not exist

=== Get a plan

....
curl -XGET http://ip:port/rate-limit-plans/{RateLimitingPlanId}
....

Return a plan:
....
{
	"planId": "65b94d87-b077-4994-bc82-ab87c4e68313",
	"planName": "oldPlanName",
	"transitLimits": [{
			"name": "receivedMailsPerHour",
			"periodInSeconds": 3600,
			"count": 100,
			"size": 2048
		},
		{
			"name": "receivedMailsPerDay",
			"periodInSeconds": 86400,
			"count": 1000,
			"size": 4096
		}
	],
	"relayLimits": [{
		"name": "relayMailsPerHour",
		"periodInSeconds": 3600,
		"count": 100,
		"size": 2048
	}],
	"deliveryLimits": [{
		"name": "deliveryMailsPerHour",
		"periodInSeconds": 3600,
		"count": 100,
		"size": 2048
	}]
}
....

Return codes:

- `200` Get the plan successfully
- `400` Invalid request
- `404` Plan does not exist

=== Get all plans

....
curl -XGET http://ip:port/rate-limit-plans
....

Return all existing plans:
....
[{
		"planId": "524acec6-7910-4137-b862-7ec1ab048404",
		"planName": "plan1",
		"transitLimits": [{
				"name": "receivedMailsPerHour",
				"periodInSeconds": 3600,
				"count": 100,
				"size": 2048
			},
			{
				"name": "receivedMailsPerDay",
				"periodInSeconds": 86400,
				"count": 1000,
				"size": 4096
			}
		],
		"relayLimits": [{
			"name": "relayMailsPerHour",
			"periodInSeconds": 3600,
			"count": 100,
			"size": 2048
		}],
		"deliveryLimits": [{
			"name": "deliveryMailsPerHour",
			"periodInSeconds": 3600,
			"count": 100,
			"size": 2048
		}]
	},
	{
		"planId": "2fc6b2d7-9b62-42f0-aa8a-5ab62168e0c5",
		"planName": "plan2",
		"transitLimits": [{
				"name": "receivedMailsPerHour",
				"periodInSeconds": 3600,
				"count": 100,
				"size": 2048
			},
			{
				"name": "receivedMailsPerDay",
				"periodInSeconds": 86400,
				"count": 1000,
				"size": 4096
			}
		],
		"relayLimits": [{
			"name": "relayMailsPerHour",
			"periodInSeconds": 3600,
			"count": 100,
			"size": 2048
		}],
		"deliveryLimits": [{
			"name": "deliveryMailsPerHour",
			"periodInSeconds": 3600,
			"count": 100,
			"size": 2048
		}]
	}
]
....

Return codes:

- `200` Get all plans successfully

=== Attach a plan to a user
....
curl -XPUT http://ip:port/users/{username}/rate-limit-plans/{planId}
....

Attach a rate limiting plan to a user. This also can be used to reattach a new plan to that user.

Return codes:

- `204` Attached the plan to the user successfully
- `400` Invalid request
- `404` Either plan or user is not found

=== Get list of users belonging to a plan
....
curl -XGET http://ip:port/rate-limit-plans/{planId}/users
....

Return users belong to a plan:
....
[
    "bob@linagora.com",
    "andre@linagora.com"
]
....

Return codes:

- `200` Get all users belong to that plan successfully
- `400` Invalid request
- `404` Plan is not found

=== Get plan of a user
....
curl -XGET http://ip:port/users/{username}/rate-limit-plans
....

Return rate limiting planId attached to that user:
....
{
    "planId": "02242f08-515c-4170-945e-64afa991f149"
}
....

Return codes:

- `200` Get plan of that user successfully
- `400` Invalid request
- `404` Either user is not found or that user does not have a plan.

=== Revoke plan of a user
....
curl -XDELETE http://ip:port/users/{username}/rate-limit-plans
....

Revoke the plan attached to that user.

Return codes:

- `204` Revoke plan of that user successfully
- `400` Invalid request
- `404` User is not found