= Contact Autocomplete
:navtitle: Contact Autocomplete

TMail allows users to have an easy and performant contact autocomplete experience.

Contacts can be stored in many ways in TMail:

- storing recipients as personal contacts when sending a mail via a mailet
- synchronisation with LDAP for all domain contacts via a LSC script
- synchronization with external third-party contact app via RabbitMQ

The user is able to autocomplete over his personal contacts and domain contacts via a JMAP method.

== Storing account contacts when sending mails

An administrator needs to rely on the `ContactsCollection` mailet in `mailetcontainer.xml` configuration file
in order to extract the recipient contacts of a message and index them asynchronously. This mailet also stores
them as JSON in a specified message attribute.

For example:

....
<mailet match="SenderIsLocal" class="com.linagora.tmail.mailets.ContactsCollection">
    <attribute>ExtractedContacts</attribute>
</mailet>
....

== Manage domain contacts via WebAdmin

An administrator can manage domain contacts using xref:tmail-backend/webadmin.adoc#_domain_contacts[Domain contacts management routes]:

- Creating/updating/getting/removing contacts to a domain
- Listing contacts from a domain
- Listing all contacts regardless of their domain

Note that the LSC script will use these routes as well to synchronize domain contacts from your LDAP to TMail.

== Running LSC scripts to synchronize contacts from a LDAP

You can use LSC scripts to synchronize your contacts from a LDAP to TMail domain contacts.

For this, you should use the link:https://github.com/linagora/tmail-lsc[TMail LSC plugin].

For more information about how to run that script for the synchronization, you can read the `README.md` of the project.
You will find what you need to link:https://github.com/linagora/tmail-lsc#configuration[configure] and
link:https://github.com/linagora/tmail-lsc#usage[use] the LSC plugin and also more information regarding
link:https://github.com/linagora/tmail-lsc#domain-contact-synchronization[domain contact synchronization].

== Synchronizing account contacts with third-party applications via RabbitMQ

If you need to synchronize contacts with TMail from an external third-party contact application, you can also use RabbitMQ.

You will need to configure TMail to connect to a RabbitMQ instance that will consume messages sent by the third-party app
on a dedicated queue.

In your `rabbitmq.properties` file in TMail, you need to add those extra fields:

- `address.contact.uri`: the URI of RabbitMQ having messages related to contacts from the third-party app.
- `address.contact.user`: the username to access the RabbitMQ instance.
- `address.contact.password`: the password to access the RabbitMQ instance.
- `address.contact.queue`: the queue name for contacts on RabbitMQ.

TMail will create an exchange for the contact queue depending on the name of the latest, following this pattern:
`TmailExchange-{address.contact.queue}`.

In addition, as well, TMail will create a queue and exchange for dead letters, meaning every message failing to be
consumed correctly to TMail will be stored there where you can check, investigate what was wrong, replay them, ...
Those queues are named according to the following pattern:

- Dead letter exchange name = "TmailQueue-dead-letter-exchange-{address.contact.exchange}"
- Dead letter queue name = "TmailQueue-dead-letter-queue-{address.contact.queue}"

Then you need to configure your third-party app to send message to the contact exchange and TMail will listen to the
bound queue and consume them.

For this, you need to respect the structure of the contact message declared as follow:

- *type*: `String` What type of operation you want to do on that contact. There is 3 possibilities here:
  * `addition` Adding a new contact
  * `removal` Removing a contact
  * `update` Updating the names of a contact
- *scope*: `String` The scope that the contact is targeted to. There is actually 2:
  * `user`: The contact is personal to the user
  * `domain`: The contact belongs to a domain
- *owner*: `String` The entity the contact belongs to. If the scope is `user`, the owner should be the user it belongs
to. If the scope is `domain`, the owner should be the domain it belongs to.
- *entry*: `MessageEntry` The entry with the detailed information of the contact.
A `MessageEntry` is composed of the following fields:
  * *address*: `String` The mail address of the contact. It has to be a valid mail address.
  * *firstname*: `String` The first name of the contact. It's optional.
  * *surname*: `String` the surname of the contact. It's optional.

For example:

- Adding a user contact:
....
{
  "type": "addition",
  "scope": "user",
  "owner" : "bob@domain.tld",
  "entry": {
    "address": "alice@domain.tld",
    "firstname": "Alice",
    "surname": "Watson"
  }
}
....

- Removing a domain contact:
....
{
  "type": "removal",
  "scope": "domain",
  "owner" : "domain.tld",
  "entry": {
    "address": "alice@domain.tld",
    "firstname": "Alice",
    "surname": "Watson"
  }
}
....

- Updating the name of an existing user contact:
....
{
  "type": "update",
  "scope": "user",
  "owner" : "bob@domain.tld",
  "entry": {
    "address": "alice@domain.tld",
    "firstname": "Bob",
    "surname": "Parker"
  }
}
....

We also provide an integration with openpaas to synchronize contacts from openpaas to TMail. xref:ROOT:tmail-backend/features/openpaas-integration.adoc[Read more]...

== Autocomplete with JMAP

The client can easily get an autocomplete over its domain and account contacts via a simple JMAP method.

The autocomplete does a full search on the email address, while the search on names is simpler as we only do it
from the first characters. The search for a contact is also not case-sensitive.

xref:tmail-backend/jmap-extensions/contactAutocomplete.adoc[Read more]...
