= LDAP mailing lists
:navtitle: LDAP mailing lists

Twake Mail allows binding mailing lists resolution onto LDAP groups.

This can be done through the `LDAPMailingList` mailet.

The list address is held by a configurable LDAP attribute of the LDAP group representing the list, and is resolved to
the list of members of the group.

Twake mail define some sender controls, defined by the business category of the LDAP group:

 - *openList(default) every body can send mails to the list
 - *internalList only james users can send mail to the list
 - *memberRestrictedList only members of the list can send mail to the list
 - *ownerRestrictedList only owners of the list can send mail to the list
 - *domainRestrictedList only members of the domain can send mail to the list

Note that member and owner resolution is recursive: LDAP groups will be expended to their members.


See xref:tmail-backend/configure/ldap-mailing-list.adoc[this page] in order to configure this feature.

== Sample LDIF

....
dn: ou=people, dc=james,dc=org
ou: people
objectClass: organizationalUnit

dn: ou=lists, dc=james,dc=org
ou: lists
objectClass: organizationalUnit

dn: uid=james-user, ou=people, dc=james,dc=org
objectClass: inetOrgPerson
uid: james-user
cn: james-user
sn: james-user
mail: james-user@james.org
userPassword: secret
description: abcdef

dn: uid=james-user2, ou=people, dc=james,dc=org
objectClass: inetOrgPerson
uid: james-user2
cn: james-user2
sn: james-user2
mail: james-user2@james.org
userPassword: secret
description: abcdef

dn: uid=james-user3, ou=people, dc=james,dc=org
objectClass: inetOrgPerson
uid: james-user3
cn: james-user3
sn: james-user3
mail: james-user3@james.org
userPassword: secret
description: abcdef

dn: uid=bob, ou=people, dc=james,dc=org
objectClass: inetOrgPerson
uid: bob
cn: bob
sn: bob
mail: bob@james.org
userPassword: secret
description: Extra user

dn: cn=group3, ou=lists, dc=james,dc=org
objectclass: groupofnames
businessCategory: internalList
cn: group3
ou: lists
description: group3@lists.james.org
member: uid=james-user3,ou=people,dc=james,dc=org
member: uid=james-user2,ou=people,dc=james,dc=org
....