= TMail Rate Limiting
:navtitle: TMail Rate Limiting

Manage email rate limiting plans and apply them to your users!

TMail Rate Limiting enable the administrator to manage rate limiting of users:

- Administrator can manage rate limiting for each user
- Administrator can configure mailet configuration, so it can retrieve rate limiting and apply to according users

== Manage rate limiting plans via webadmin

The administrator can manage rate limiting using xref:tmail-backend/webadmin.adoc#_rate_limiting[Rate Limiting Plan Management Routes]:

- Updating/getting rate limiting for users.

== Apply rate limiting via mailets

TMail provides mailets that enforce these limits during mail processing:

- `SentRateLimiting`: applies rate limiting for the sender of the email.
- `ReceivedRateLimiting`: applies rate limiting for the recipients of the email.

Example configurations:

```
    <mailet match="SenderIsLocal" class="com.linagora.tmail.mailets.SentRateLimiting">
        <keyPrefix>some-prefix</keyPrefix>
        <exceededProcessor>tooMuchMails</exceededProcessor>
        <mailsPerMinuteDefault>10</mailsPerMinuteDefault/>
        <mailsPerHourDefault>100</mailsPerHourDefault/>
        <mailsPerDayDefault>1000</mailsPerDayDefault/>
    </mailet>
    <mailet match="RecipientIsLocal" class="com.linagora.tmail.mailets.ReceivedRateLimiting">
        <keyPrefix>some-prefix</keyPrefix>
        <precision>1s</precision>
        <exceededProcessor>tooMuchMails</exceededProcessor>
        <mailsPerMinuteDefault>10</mailsPerMinuteDefault/>
        <mailsPerHourDefault>100</mailsPerHourDefault/>
        <mailsPerDayDefault>1000</mailsPerDayDefault/>
    </mailet>
```

See according mailet Javadoc for more details.
