= Calendar event reply
:navtitle: calendar event reply

Allows users to reply to calendar event invitations. They can respond with Accept, Deny, or Tentative statuses, corresponding to three methods: `CalendarEvent/accept`, `CalendarEvent/reject`, and `CalendarEvent/maybe`, respectively.

== Additions to the capability object

Servers supporting the calendar event parse extension need
to advertise it through the session capabilities:
....
com:linagora:params:calendar:event
....

The associated object sample:

....
{
    "replySupportedLanguage": ["en", "fr"]
}
....

The replySupportedLanguage object contains a list of languages supported by the application for determining email templates.

== CalendarEvent/accept

This method allows the client to accept a calendar event invitation.
The CalendarEvent/accept method takes the following arguments:

- *accountId*: `Id` The id of the account to use.
- *blobIds*: `Id[]` The ids correspond to the blob of calendar event invitations file that the user intends to accept.
They must be validated to ensure they can be parsed using the `CalendarEvent/parse` method for verification.
- *language*: `String`. Optional, Default is `en`. The language tag that the client wants the server to use when determining the email template.

The response object contains the following arguments:

- *accountId*: `Id` The id of the account used for the call.
- *accepted*: `Id[CalendarEvent[]]|null` A list of ids of the calendar events that were successfully accepted, or `null` if none.
- *notFound*: `Id[]|null` A list of blob ids given that could not be found, or `null` if none.
- *notAccepted*: `Id[SetError]|null`  A map of the blobId to a SetError object for each calendar event that failed to reply, or null if all successful.

== Example

The client makes a request to accept a calendar event invitation:

....
{
	"using": ["urn:ietf:params:jmap:core", "com:linagora:params:calendar:event"],
	"methodCalls": [
        [ "CalendarEvent/accept", {
            "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
            "blobIds": ["0f9f65ab-dc7b-4146-850f-6e4881093965"]
        }, "c1"]
	]
}
....

The server responds:

```
[[ "CalendarEvent/accept",
{
    "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
    "accepted": [ "0f9f65ab-dc7b-4146-850f-6e4881093965" ],
}, "c1" ]]
```

In the case that a blob id is not found, the server would respond:

```
[[ "CalendarEvent/accept",
{
    "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
    "notFound": [ "0f9f65ab-dc7b-4146-850f-6e4881093965" ]
}, "c1" ]]
```

If the blob id has been found but is not generate & reply email, the server would respond:

```
[[ "CalendarEvent/accept",
{
    "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
    "notAccepted": {
        "0f9f65ab-dc7b-4146-850f-6e4881093965": {
            "type": "invalidPatch",
            "description": "The calendar must have REQUEST as a method"
        }
    }
}, "c1" ]]
```

== CalendarEvent/reject
Similarly to CalendarEvent/accept, CalendarEvent/reject function in a similar manner.
However, in the response properties, 'rejected' replace 'accepted', while 'notRejected' replace 'notAccepted'.

== CalendarEvent/maybe
Similarly to CalendarEvent/accept, CalendarEvent/maybe function in a similar manner.
However, in the response properties, 'maybe' replace 'accepted', while 'notMaybe' replace 'notAccepted'.
