= Calendar event reply
:navtitle: calendar event reply

Allows users to reply to calendar event invitations. They can respond with Accept, Deny, or Tentative statuses, corresponding to three methods: `CalendarEvent/accept`, `CalendarEvent/reject`, and `CalendarEvent/maybe`, respectively.

== Additions to the capability object

Servers supporting the calendar event parse extension need
to advertise it through the session capabilities:
....
com:linagora:params:calendar:event
....

The associated object sample:

....
{
    "replySupportedLanguage": ["en", "fr"],
    "supportFreeBusyQuery": true
}
....

- The `replySupportedLanguage` object contains a list of languages supported by the application for determining email templates.
- The `supportFreeBusyQuery` object is a boolean value that indicates whether the server supports the freeBusy query in the response of the `CalendarEventAttendance/get` method.

== CalendarEvent/accept

This method allows the client to accept a calendar event invitation.
The CalendarEvent/accept method takes the following arguments:

- *accountId*: `Id` The id of the account to use.
- *blobIds*: `Id[]` The ids correspond to the blob of calendar event invitations file that the user intends to accept.
They must be validated to ensure they can be parsed using the `CalendarEvent/parse` method for verification.
- *language*: `String`. Optional, Default is `en`. The language tag that the client wants the server to use when determining the email template.

The response object contains the following arguments:

- *accountId*: `Id` The id of the account used for the call.
- *accepted*: `Id[CalendarEvent[]]|null` A list of ids of the calendar events that were successfully accepted, or `null` if none.
- *notFound*: `Id[]|null` A list of blob ids given that could not be found, or `null` if none.
- *notAccepted*: `Id[SetError]|null`  A map of the blobId to a SetError object for each calendar event that failed to reply, or null if all successful.

== Example

The client makes a request to accept a calendar event invitation:

....
{
	"using": ["urn:ietf:params:jmap:core", "com:linagora:params:calendar:event"],
	"methodCalls": [
        [ "CalendarEvent/accept", {
            "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
            "blobIds": ["0f9f65ab-dc7b-4146-850f-6e4881093965"]
        }, "c1"]
	]
}
....

The server responds:

```
[[ "CalendarEvent/accept",
{
    "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
    "accepted": [ "0f9f65ab-dc7b-4146-850f-6e4881093965" ],
}, "c1" ]]
```

In the case that a blob id is not found, the server would respond:

```
[[ "CalendarEvent/accept",
{
    "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
    "notFound": [ "0f9f65ab-dc7b-4146-850f-6e4881093965" ]
}, "c1" ]]
```

If the blob id has been found but is not generate & reply email, the server would respond:

```
[[ "CalendarEvent/accept",
{
    "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
    "notAccepted": {
        "0f9f65ab-dc7b-4146-850f-6e4881093965": {
            "type": "invalidPatch",
            "description": "The calendar must have REQUEST as a method"
        }
    }
}, "c1" ]]
```

== CalendarEvent/reject
Similarly to CalendarEvent/accept, CalendarEvent/reject function in a similar manner.
However, in the response properties, 'rejected' replace 'accepted', while 'notRejected' replace 'notAccepted'.

== CalendarEvent/maybe
Similarly to CalendarEvent/accept, CalendarEvent/maybe function in a similar manner.
However, in the response properties, 'maybe' replace 'accepted', while 'notMaybe' replace 'notAccepted'.

== CalendarEventAttendance/get
This method allow clients to get the attendance status of a calendar event invitation.
The CalendarEventAttendance/get method takes the following arguments:

- *accountId*: `Id` The id of the account to use.
- *blobIds*: `Id[]` The ids correspond to the blob of calendar event invitation files that the user wants to query for status.

The response object contains the following arguments:

- *accountId*: `Id` The id of the account used for the call.
- *list*: `CalendarEventAttendance[]` A list of attendance records.
- *notFound*: `Id[]|null` A list of blob ids given that could not be found, or `null` if none.
- *notDone*: `Id[SetError]|null`  A map of the blobId to a SetError object for each calendar event that failed to reply, or null if all successful.

The `CalendarEventAttendance` object is defined as follows:

- *blobId*: `Id` (required) The id of the blob of the calendar event.
- *attendanceStatus*: `String` (required) The attendance status of the user for the calendar event. Possible values are: `accepted`, `rejected`, `tentativelyAccepted`, `needsAction`.
- *isFree*: `Boolean` A boolean value indicating whether the user is free at the time of the event. `true` if the user is free, `false` otherwise.

The associated `replySupportedLanguage` capability property is not needed for this method to function.

The associated `supportFreeBusyQuery` capability property is needed for the server to return the `isFree` property.

Note: The sum of sizes of arrays `list`, `notFound` and `notDone` must be equal to the size of `blobIds`, otherwise the server must return an error.

== Example

The client makes a request to get the attendance status of calendar event invitations `1_5` that was previously accepted and `1_3` that was rejected:

....
{
    "using": ["urn:ietf:params:jmap:core", "com:linagora:params:calendar:event"],
    "methodCalls": [
        [ "CalendarEventAttendance/get", {
            "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
            "blobIds": ["1_5", "1_3"]
        }, "c1"]
    ]
}
....

The server responds:

[source]
----

[[ "CalendarEventAttendance/get",
{
    "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
    "list" : [
      {
        "blobId": "1_3",
        "attendanceStatus": "rejected",
        "isFree": true
      },
      {
        "blobId": "1_5",
        "attendanceStatus": "accepted",
        "isFree":  true
      }
    ]
}, "c1" ]]
----

In the case that a blob id is not found or not accessible for current user, the server would respond:

[source]
----
[[ "CalendarEventAttendance/get",
{
    "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
    "list" : [],
    "notFound": ["0f9f65ab-dc7b-4146-850f-6e4881093965" ]
}, "c1" ]]
----

If the blob id was in an invalid format, the server would respond:

[source]
----
[[ "CalendarEventAttendance/get",
{
    "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
    "list" : [],
    "notDone": {
        "BAD_BLOB_ID": {
            "type": "invalidArguments",
            "description": "Invalid BlobId 'BAD_BLOB_ID'. Blob id needs to match this format: {message_id}_{partId1}_{partId2}_..."
        }
    }
}, "c1" ]]
----

If the number of blob ids in the request exceeds the limit (currently 16), the server would respond:

----
[
    "error",
    {
        "type": "requestTooLarge",
        "description": "The number of ids requested by the client exceeds the maximum number the server is willing to process in a single method call"
    },
    "c1"
]
----

If the event query get a scheduling conflict, `isFree` property will be `false`

----
[[ "CalendarEventAttendance/get",
{
    "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
    "list" : [
      {
        "blobId": "1_5",
        "attendanceStatus": "needsAction",
        "isFree":  false
      }
    ]
}, "c1" ]]
----

In this response, the server has detected events "1_5" conflict with another event in the same time slot.