= Calendar event parse
:navtitle: calendar event parse

Allows users to parse calendar events for getting event information from the blob id of the calendar file (.ics).

== Additions to the capability object

Servers supporting the calendar event parse extension need
to advertise it through the session capabilities:
....
com:linagora:params:calendar:event
....

The associated object is empty.

== CalendarEvent/parse

This method is based on:

- Parsing a Received MDN method as described in the RFC-9007
- Draft JMAP CalendarEvent (https://datatracker.ietf.org/doc/html/draft-ietf-jmap-calendars)
- iCalendar message RFC-5545

The request object requires the following properties:

- *accountId*: `Id` The id of the account to use.
- *blobIds*: `[Id]` An array of calendar blob ids that the user wants to parse.

The response object contains the following properties:

- *accountId*: `Id` The id of the account to use.
- *parsed*: `Map[BlobId]` and the corresponding calendar parse result.
- *notFound*: `[BlobId]` is not found.
- *notParsable*: `[BlobId]` has been found but is not parsable.

The `parsed` value contains the following properties (the properties below match with the properties defined in RFC-5545 and RFC-5546):

- `uid`: unique identifier of the event ~ UID (iCalendar)
- `title`: title of the event ~ SUMMARY
- `description`: description of the event ~ DESCRIPTION
- `start`: Start time of the event ~ DTSTART
- `end`: End time of the event ~ DTEND
- `utcStart`: Start time of the event in UTC time zone
- `utcEnd`: End time of the event in UTC time zone
- `duration`: duration of the event ~ DURATION
- `timeZone`: time zone of the start/end time ~ TZID
- `location`: location of the event ~ LOCATION
- `method`: method of the event: REQUEST someone to attend an event, CANCEL an event... ~ [METHOD](https://www.rfc-editor.org/rfc/rfc5546.html#section-3.2)
- `sequence`: modification number of the event ~ SEQUENCE
- `privacy`: determine if the event is publicly visible ~ [CLASS](https://www.rfc-editor.org/rfc/rfc5545#section-3.8.1.3)
- `priority`: priority of the event (0 -> 9) ~ PRIORITY
- `freeBusyStatus`: defines if the event is transparent to busy time searches ~ [TRANSP](https://www.rfc-editor.org/rfc/rfc5545#section-3.8.2.7)
- `status`: indicates that a meeting is tentative, confirmed, or cancelled ~ [STATUS](https://www.rfc-editor.org/rfc/rfc5545#section-3.8.1.11)
- `organizer`: the organizer of the event, contains name (CN) and mail (mailto)
- `participants`: a collection of attendees (ATTENDEE)
- `recurrenceRules` RecurrenceRule[]: a collection of recurrence rules [RRULE](https://www.rfc-editor.org/rfc/rfc8984.html#name-recurrence-properties)
- `excludedRecurrenceRules` RecurrenceRule[]: a collection of excluded recurrence rules [EXRULE](https://www.rfc-editor.org/rfc/rfc8984.html#section-4.3.4)
- `extensionFields`: contains custom event headers.

Each `participant` contains information:

- `name`: name of the participant
- `mailto`: mail address of the participant
- `kind`: "CUTYPE", to indicate the type of calendar user
- `role`: "ROLE", for the intended role that the attendee will have in the calendar component
- `participationStatus`: "PARTSTAT", for the status of the attendee's participation
- `expectReply`: Boolean. "RSVP", for indicating whether the favor of a reply is requested

Each `recurrenceRule` contains information:

- `frequency`: the time span covered by each iteration
- `interval`: the interval of iteration periods at which the recurrence
repeats
- `rscale`: the calendar system in which this recurrence rule
operates
- `skip`: the behavior to use when the expansion of the recurrence
produces invalid dates
- `firstDayOfWeek`: the day on which the week is considered to start,
represented as a lowercase, abbreviated, and two-letter English
day of the week
- `byDay`: days of the week on which to repeat
- `byMonthDay`: the days of the month on which to repeat
- `byMonth`: the months in which to repeat
- `byYearDay`: the days of the year on which to repeat
- `byWeekNo`: the weeks of the year in which to repeat
- `byHour`: the hours of the day in which to repeat
- `byMinute`: the minutes of the hour in which to repeat
- `bySecond`: the seconds of the minute in which to repeat
- `bySetPosition`: the occurrences within the recurrence interval to
include in the final results
- `count`: the number of occurrences at which to range-bound the
recurrence
- `until`: the date-time at which to finish recurring. The last
occurrence is on or before this date-time


== Example

The client makes a request to parse the calendar event with a BlobId

....
{
	"using": ["urn:ietf:params:jmap:core", "com:linagora:params:calendar:event"],
	"methodCalls": [
        [ "CalendarEvent/parse", {
            "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
            "blobIds": ["0f9f65ab-dc7b-4146-850f-6e4881093965"]
        }, "c1"]
	]
}
....

The server responds:

```
[[ "CalendarEvent/parse",
{
    "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
    "parsed": {
        "0f9f65ab-dc7b-4146-850f-6e4881093965": {
            "uid": "ea127690-0440-404b-af98-9823c855a283",
            "title": "Gatling: break LemonLDAP!",
            "description": "Let's write some basic OIDC benchmarks",
            "start": "2023-02-09T10:00:00",
            "duration": "PT2H0M0S",
            "end": "2023-02-09T12:00:00",
            "timeZone": "Asia/Ho_Chi_Minh",
            "location": "5 Dien Bien Phu, Ha Noi",
            "method": "REQUEST",
            "sequence": 0,
            "priority": 5,
            "freeBusyStatus": "busy",
            "privacy": "public",
            "organizer": {
                "name": "Benoît TELLIER",
                "mailto": "btellier@linagora.com"
            },
            "participants": [{
                    "name": "Benoît TELLIER",
                    "mailto": "btellier@domain.tld",
                    "kind": "individual",
                    "role": "chair",
                    "participationStatus": "accepted",
                    "expectReply": false
                },
                {
                    "name": "Van Tung TRAN",
                    "mailto": "vttran@domain.tld",
                    "kind": "individual",
                    "role": "requested-participant",
                    "participationStatus": "needs-action",
                    "expectReply": true
                }
            ],
            "extensionFields": {
                "X-OPENPAAS-VIDEOCONFERENCE": ["https://jitsi.linagora.com/abcd"],
                "X-OPENPAAS-CUSTOM-HEADER1": ["whatever1", "whatever2"]
            },
            "recurrenceRules":
               [{   "frequency": "yearly",
                     "byDay": [ "mo" ],
                     "byMonth": [ "10" ],
                     "bySetPosition": [ 1, 2 ],
                     "until":"2024-01-11T09:00:00Z"
               }]
        }
    }
}, "c1" ]]
```

In the case that a blob id is not found, the server would respond:

```
[[ "CalendarEvent/parse",
{
    "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
    "notFound": [ "0f9f65ab-dc7b-4146-850f-6e4881093965" ]
}, "c1" ]]
```

If the blob id has been found but is not parsable, the server would respond:

```
[[ "CalendarEvent/parse",
{
    "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
    "notParsable": [ "0f9f65ab-dc7b-4146-850f-6e4881093965" ]
}, "c1" ]]
```