= Calendar event parse
:navtitle: calendar event parse

Allows users to parse calendar events for getting event information from the blob id of the calendar file (.ics).

== Additions to the capability object

Servers supporting the calendar event parse extension need
to advertise it through the session capabilities:
....
com:linagora:params:calendar:event
....

The associated object is empty.

== CalendarEvent/parse

This method allows the client to parse blobs as `iCalendars` [@!RFC5545] to get `CalendarEvent` objects
(defined in https://datatracker.ietf.org/doc/draft-ietf-jmap-calendars). This can be used
to parse and display calendar events information to the end user.

The following metadata properties on the CalendarEvent objects will be `null` if requested:

- id
- baseEventId
- calendarIds
- isDraft
- isOrigin

The `CalendarEvent/parse` method takes the following arguments:

- *accountId*: `Id` The id of the account to use.
- *blobIds*: `Id[]` The ids of the blobs to parse.
- *properties*: `String[]` If supplied, only the properties listed in the array are returned for each `CalendarEvent`
object. If omitted, defaults to all the properties.

The response object contains the following arguments:

- *accountId*: `Id` The id of the account used for the call.
- *parsed*: `Id[CalendarEvent[]]|null` A map of blob ids to parsed `CalendarEvent` objects representations for each
successfully parsed blob, or `null` if none.
- *notFound*: `Id[]|null` A list of blob ids given that could not be found, or `null` if none.
- *notParsable*: `Id[]|null` A list of blob ids given that corresponded to blobs that could not be parsed as
CalendarEvents, or `null` if none.

Parsed `iCalendars` are to be converted into `CalendarEvent` objects following the process defined in
https://datatracker.ietf.org/doc/draft-ietf-calext-jscalendar-icalendar.

== Example

The client makes a request to parse the calendar event from a blob id:

....
{
	"using": ["urn:ietf:params:jmap:core", "com:linagora:params:calendar:event"],
	"methodCalls": [
        [ "CalendarEvent/parse", {
            "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
            "blobIds": ["0f9f65ab-dc7b-4146-850f-6e4881093965"]
        }, "c1"]
	]
}
....

The server responds:

```
[[ "CalendarEvent/parse",
{
    "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
    "parsed": {
        "0f9f65ab-dc7b-4146-850f-6e4881093965": [
            {
                "uid": "ea127690-0440-404b-af98-9823c855a283",
                "title": "Gatling: break LemonLDAP!",
                "description": "Let's write some basic OIDC benchmarks",
                "start": "2023-02-09T10:00:00",
                "duration": "PT2H0M0S",
                "end": "2023-02-09T12:00:00",
                "timeZone": "Asia/Ho_Chi_Minh",
                "location": "10 Thai Ha, Ha Noi",
                "method": "REQUEST",
                "sequence": 0,
                "priority": 5,
                "freeBusyStatus": "busy",
                "privacy": "public",
                "organizer": {
                    "name": "Bob SMITH",
                    "mailto": "bsmith@example.com"
                },
                "participants": [{
                        "name": "Bob SMITH",
                        "mailto": "bsmith@example.com",
                        "kind": "individual",
                        "role": "chair",
                        "participationStatus": "accepted",
                        "expectReply": false
                    },
                    {
                        "name": "Alice DOE",
                        "mailto": "adoe@example.com",
                        "kind": "individual",
                        "role": "requested-participant",
                        "participationStatus": "needs-action",
                        "expectReply": true
                    }
                ],
                "extensionFields": {
                    "X-VIDEOCONFERENCE": ["https://jitsi.linagora.com/abcd"],
                    "X-CUSTOM-HEADER1": ["whatever1", "whatever2"]
                },
                "recurrenceRules":[
                    {
                        "frequency": "yearly",
                        "byDay": [ "mo" ],
                        "byMonth": [ "10" ],
                        "bySetPosition": [ 1, 2 ],
                        "until":"2024-01-11T09:00:00Z"
                   }
                ],
                "recurrenceId": "20250409T080000Z"
            },
            ...
        ]
    }
}, "c1" ]]
```

In the case that a blob id is not found, the server would respond:

```
[[ "CalendarEvent/parse",
{
    "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
    "notFound": [ "0f9f65ab-dc7b-4146-850f-6e4881093965" ]
}, "c1" ]]
```

If the blob id has been found but is not parsable, the server would respond:

```
[[ "CalendarEvent/parse",
{
    "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
    "notParsable": [ "0f9f65ab-dc7b-4146-850f-6e4881093965" ]
}, "c1" ]]
```