= Deleted messages vault
:navtitle: deleted messages vault

Allows users to recover deleted messages in their vault.

This is done by creating `EmailRecoveryAction` that restores deleted emails in the vault into users `Restored-Messages`
mailboxes. This mailbox carries the `restored messages` role.

== Additions to the capability object

Servers supporting the deleted message vault extension need to advertise it through the session capabilities:
....
com:linagora:params:jmap:messages:vault
....

The associated object have the following fields:

- `maxEmailRecoveryPerRequest`: *String*, defaulting to `"5"`. Maximum number of emails a given `EmailRecoveryAction` would
allow to recover. Note that this number is serialized as a JSON String, e.g. `"5"`.
- `restorationHorizon`: *String | null*, defaulting to `15 days`. Horizon past which users can no longer recover emails on their own, formatted into a plurialization correct String, like `1 day 12 hours`.

== EmailRecoveryAction object

This represents the recovery action for deleted items in the vault.

It has the following properties:

 - `id`: *Id* (server set) the object identifier.
 - `deletedBefore`: *UTC date | null*. Immutable. If set this EmailRecoveryAction would restore only emails deleted before the aforementioned date.
 - `deletedAfter`: *UTC date | null*. Immutable. If set this EmailRecoveryAction would restore only emails deleted after the aforementioned date.
 - `receivedBefore`: *UTC date | null*. Immutable. If set this EmailRecoveryAction would restore only emails received before the aforementioned date.
 - `receivedAfter`: *UTC date | null*. Immutable. If set this EmailRecoveryAction would restore only emails received after the aforementioned date.
 - `hasAttachment`: *Boolean | null*. Immutable. If set this EmailRecoveryAction would restore only email whose `hasAttachment` property matches this field.
 - `subject`: *String | null*. Immutable. If set this EmailRecoveryAction would restore only email whose `subject` property contains this field.
 - `sender`: *String | null*. Immutable. If set this EmailRecoveryAction would restore only email whose `from` property matches this field. Needs to be a valid email address.
 - `recipients`: *String[] | null*. Immutable. If set this EmailRecoveryAction would restore only email whose `to`, `cc` or `bcc` properties matches all of the mentioned email addresses.
 Needs to be a valid email addresses.
 - `successfulRestoreCount`: *UnsignedInt* (server-set). Number of successful restored messages.
 - `errorRestoreCount`: *UnsignedInt* (server-set). Number of failed restored messages.
 - `status`: *Status*. The status of the task.

*Status* can have the following values:

 - `waiting`: the task is planned and waits to be executed
 - `inProgress`: the task is currently being executed
 - `completed`: the task is done. Its execution did succeed.
 - `failed`: the task execution failed.
 - `canceledRequested`: the cancellation of the task was requested but is not effective yet.
 - `canceled`: the task was canceled.

== EmailRecoveryAction/get

This method returns the underlying email recovery actions.

Similar to a standard `/get` method, with the following differences:

 - The `ids` property cannot be null.
 - The `accountId` property of the request is not required and is ignored.
 - The response carries neither `accountId` nor `state`: it only contains the `list` and `notFound` properties.

This method only supports the following properties of the `EmailRecoveryAction` object: `id`, `successfulRestoreCount`,
`errorRestoreCount`, `status`.

== EmailRecoveryAction/set

Similar to a standard `/set` method, with the following differences:

 - The `accountId` property of the request is not required and is ignored. `ifInState` is not supported.
 - The response carries neither `accountId` nor `oldState` / `newState`: it only contains the `created`, `notCreated`,
`updated` and `notUpdated` properties.

Note that `/set create` should fail when `status` property is specified.

`EmailRecoveryAction/set destroy` should fail.

Similarly, `/set update` can only be performed on the `status` property, if and only if the status is `waiting` or
`inProgress`.

We define the `invalidStatus` method level error should be returned upon status update state violation.

== Example

The client makes a request to recover email in his vault:

....
{
	"using": ["urn:ietf:params:jmap:core", "com:linagora:params:jmap:messages:vault"],
	"methodCalls": [
        ["EmailRecoveryAction/set",
          {
            "create": {
              "idclient0":  {
                "deletedBefore": "2023-02-09T10:00:00",
                "deletedAfter": "2023-02-09T09:00:00",
                "receivedBefore": "2023-02-09T10:00:00",
                "receivedAfter": "2023-02-09T09:00:00",
                "hasAttachment": true,
                "subject": "Simple topic",
                "sender": "bob@domain.tld",
                "recipients": ["alice@domain.tld"]
              }
            }
          },
          "#0"
       ]
	]
}
....

The server responds:

....
[["EmailRecoveryAction/set",
  {
    "created" {
        "idclient0": { "id": "2034-495-05857-57abcd-0876664" }
      },
      "notCreated: []
   },
   "#0"
]]
....

The client can then poll to get status updates:

....
["EmailRecoveryAction/get",
  {
    "ids": ["2034-495-05857-57abcd-0876664"],
    "properties": ["status"]
   },
   "#0"
]
....

Would return:

....
["EmailRecoveryAction/get",
  {
    "list": [{
        "id: "2034-495-05857-57abcd-0876664",
        "status": "inProgress"
    }],
    "notFound": []
   },
   "#0"
]
....

The client can then cancel the `EmailRecoveryAction`:

....
["EmailRecoveryAction/set",
  {
    "update": {
        "2034-495-05857-57abcd-0876664": {"status":"canceled"}
      }
   },
   "#0"
]
....

Would return:

....
["EmailRecoveryAction/set",
  {
    "updated" : {"2034-495-05857-57abcd-0876664": null },
    "notUpdated": {}
   },
   "#0"
]
....

Attempting to cancel the task again should be rejected:
....
["EmailRecoveryAction/set",
  {
    "update": {
        "2034-495-05857-57abcd-0876664": {"status":"canceled"}
      }
   },
   "#0"
]
....

Would return:

....
["EmailRecoveryAction/set",
  {
    "updated" : {},
    "notUpdated": {
      "2034-495-05857-57abcd-0876664": {
        "type":"invalidStatus",
        "description": "Attempting to cancel an EmailRecoveryAction with an invalid status."
      }
   },
   "#0"
]
....