= JMAP Filters
:navtitle: JMAP Filters

JMAP filters allow a user to automate actions, based on specified rules, to be applied when receiving messages.

The following conditions are currently implemented:

 - `from`, `to`, `cc`, `recipient`, `subject` fields matching either completely or partially.

The following actions are currently implemented:

 - Move the message to another mailbox

== Addition to the capability object

Support for JMAP filters is advertised through the `com:linagora:params:jmap:filter` capability, associated with an
empty object.

== Filter object

The `Filter` object represents the set of rules associated to a given user. It is composed of the following fields:

 - **id**: Server-set, `Id`, immutable, must be `singleton`.

A filter is associated with a list of `Rule`.

A `Rule` object has the following properties:

 - **id**: Server-set, `Id`, immutable, the JMAP identifier.
 - **name**: `String`, the name of the rule, which can be used to hold an explanation regarding the purpose of this rule.
 - **conditionGroup**: `ConditionGroup`, when this rule should be applied.
 - **condition**: `Condition`, when this rule should be applied. This is the old property replaced by the property conditionGroup. This property is still retained to keep backend compatible with frontend that has not been updated yet. In the future, this property should be removed.
 - **action**: `Action`, what to do when the rule is applied.

A `ConditionGroup` object has the following properties:

- **conditionCombiner**: `String`, the operator to combine conditions of the rule. Must be one of `AND`, `OR`. `AND` operator means that all conditions must be met to apply the rule. `OR` operator means that at least one condition must be met.
- **conditions**: `Condition[]`, list of `Condition`.

A `Condition` object has the following properties:

- **field**: `String`, the field of the message to be evaluated. Must be one of `from`, `to`, `cc`, `recipient`, `subject`.
- **comparator**: `String`, how to compare the field against the suppied value. Must be one of `contains`, `not-contains`, `exactly-equals`, `not-exactly-equals`, `start-with`.
The comparator is case-incentive for `from`, `to`, `cc`, `recipient` fields but case-sensitive for `subject` field.
- **value**: `String`, the value the field should be evaluated against, using the comparator.

An `Action` object has the following properties:

- **markAsSeen** `Boolean` optional defaults to false. Should the matching email be marked as seen.
- **markAsImportant** `Boolean` optional defaults to false. Should the matching email be marked as important.
- **reject** `Boolean` optional defaults to false. Should the matching email be rejected.
- **withKeywords** `String[]` optional defaults to empty. The keyword to apply to matching emails.
- **appendIn**: `AppendIn`, specified the "append in mailboxes" action.
- **forwardTo**: `ForwardTo`, optional. specified the "forward" action.
- **moveTo**: `MoveTo`, optional. Specifies the "move to mailbox by name" action.

An `AppendIn` object has the following properties:

 - **mailboxIds**: `List[Id]`: The list of mailboxes to put the message in.

A `ForwardTo` object has the following properties:

 - **addresses**: `String[]`: The list of email addresses to forward the email to.
 - **keepACopy**: `Boolean`: Should the email be kept locally or not.

A `MoveTo` object has the following properties:

 - **mailboxName**: `String`. The name of the mailbox to move the message to. If the mailbox does not exist, it will be created automatically.

=== Filter/get

This is a standard `/get` call for the Filter object.

 - The `state` property reflects the internal event sourcing state.
 - This object being a singleton, only `singleton` id is associated with a value.

=== Filter/set

This is a standard `/set` call for the Filter object.

 - `ifInState` property is supported
 - `oldState` and `newState` are accurate.
 - As this is a singleton object, `create` and `destroy` are not supported for filters.

=== Push data types

A client can register for updates on the `Filter` datatype using either eventsource or websockets.

=== Example (with the property conditionGroup in the request)

....
{
	"using": ["com:linagora:params:jmap:filter"],
	"methodCalls": [
		["Filter/set", {
			"accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
			"update": {
				"singleton": [{
					"id": "1",
					"name": "My first rule",
					"conditionGroup": {
						"conditionCombiner": "AND",
						"conditions": [
							{
								"field": "subject",
								"comparator": "contains",
								"value": "question"
							},
							{
								"field": "from",
								"comparator": "contains",
								"value": "user2"
							},
						]
					}
					"action": {
						"appendIn": {
							"mailboxIds": ["42"]
						},
						"forwardTo": {
							"addresses": ["alice@james.org"],
							"keepACopy": false
						}
					}
				}]
			}
		}, "c1"],
		[
			"Filter/get",
			{
				"accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
				"ids": ["singleton"]
			},
			"c2"
		]
	]
}
....

Will return:

....
{
	"sessionState": "abcdefghij",
	"methodResponses": [
		[
			"Filter/set",
			{
				"accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
				"oldState": "-1",
				"newState": "0",
				"updated": {
					"singleton": {

					}
				}
			},
			"c1"
		],
		[
			"Filter/get", {
				"accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
				"state": "0",
				"list": [{
					"id": "singleton",
					"rules": [{
						"name": "My first rule",
						"conditionGroup": {
							"conditionCombiner": "AND",
							"conditions": [
								{
									"field": "subject",
									"comparator": "contains",
									"value": "question"
								},
								{
									"field": "from",
									"comparator": "contains",
									"value": "user2"
								},
							]
						}
						"condition": {
							"field": "subject",
							"comparator": "contains",
							"value": "question"
						},
						"action": {
							"appendIn": {
								"mailboxIds": ["42"]
							},
							"forwardTo": {
								"addresses": ["alice@james.org"],
								"keepACopy": false
							}
						}
					}]
				}],
				"notFound": []
			}, "c2"
		]
	]
}
....

=== Example (without the property conditionGroup in the request)

....
{
	"using": ["com:linagora:params:jmap:filter"],
	"methodCalls": [
		["Filter/set", {
			"accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
			"update": {
				"singleton": [{
					"id": "1",
					"name": "My first rule",
					"condition": {
						"field": "subject",
						"comparator": "contains",
						"value": "question"
					},
					"action": {
						"appendIn": {
							"mailboxIds": ["42"]
						},
						"forwardTo": {
							"addresses": ["alice@james.org"],
							"keepACopy": false
						}
					}
				}]
			}
		}, "c1"],
		[
			"Filter/get",
			{
				"accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
				"ids": ["singleton"]
			},
			"c2"
		]
	]
}
....

Will return:

....
{
	"sessionState": "abcdefghij",
	"methodResponses": [
		[
			"Filter/set",
			{
				"accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
				"oldState": "-1",
				"newState": "0",
				"updated": {
					"singleton": {

					}
				}
			},
			"c1"
		],
		[
			"Filter/get", {
				"accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
				"state": "0",
				"list": [{
					"id": "singleton",
					"rules": [{
						"name": "My first rule",
						"conditionGroup": {
							"conditionCombiner": "AND",
							"conditions": [
								{
									"field": "subject",
									"comparator": "contains",
									"value": "question"
								}
							]
						}
						"condition": {
							"field": "subject",
							"comparator": "contains",
							"value": "question"
						},
						"action": {
							"appendIn": {
								"mailboxIds": ["42"]
							},
							"forwardTo": {
								"addresses": ["alice@james.org"],
								"keepACopy": false
							}
						}
					}]
				}],
				"notFound": []
			}, "c2"
		]
	]
}
....
