= JMAP Settings
:navtitle: JMAP Settings

This extension allows clients to store per-user settings on the backend side.

== Additions to the capability object

Servers supporting the JMAP Settings extension need to advertise it through the session capabilities:
....
com:linagora:params:jmap:settings
....

The associated object has the following field:

- `readOnlyProperties`: *List[String]*. List of read-only properties the client cannot edit.

== Settings object

The `Settings` object represents a list of settings per-user used by clients to store some of their user related
configuration on the backend server.

It has the following fields:

- *id*: `Id` (immutable; server-set) The id of the object. There is only ever one Settings object,
and its id is "singleton".
- *settings*: `String[String]` Map of settings set by the client. Most of the settings are proper to what the client
needs to store on the backend, but some can be also known for some automation on the backend for a particular user
regarding TMail applications.

Example:

....
{
  "id":"singleton",
  "settings": {
    "tdrive.attachment.import.enabled": "true",
    "firebase.enabled": "true",
    "timezone": "UTC+7",
    "trash.cleanup.enabled": "true",
    "trash.cleanup.period": "weekly",
    "language": "fr",
    [...]
  }
}
....

== Methods

=== Settings/get

This is a standard “/get” method for the Settings object:

- There MUST only be exactly one Settings object in an account. It MUST have the id “singleton”.

=== Settings/set

This is a standard `/set` method for the Settings object:

- As this is a singleton object, `create` and `destroy` are not supported.
- Attempts to modify read-only settings (as listed in the `readOnlyProperties` capability property) will be rejected.

=== Examples

==== Full Settings update

The request:

....
{
  "using": ["urn:ietf:params:jmap:core", "com:linagora:params:jmap:settings"],
  "methodCalls": [
    [
      "Settings/set",
      {
        "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
        "update": {
          "singleton": {
            "settings": {
              "tdrive.attachment.import.enabled": "true",
              "firebase.enabled": "true",
              "timezone": "UTC+7",
              "appearance.theme": "dark",
              "language": "fr",
              "read.receipts.always": "false"
            }
          }
        }
      },
      "c1"
    ],
    [
      "Settings/get",
      {
        "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
        "ids": null
      },
      "c2"
    ]
  ]
}
....

Will return:

....
{
  "sessionState": "abcdefghij",
  "methodResponses": [
    ["Settings/set",
    {
      "accountId": "123",
      "newState": "1",
      "updated": {"singleton":{}}
    },
    "c1"],
    ["Settings/get",
    {
      "accountId": "123",
      "notFound": [],
      "state": "1",
      "list": [
        {
          "id": "singleton",
          "settings": {
            "tdrive.attachment.import.enabled": "true",
            "firebase.enabled": "true",
            "timezone": "UTC+7",
            "appearance.theme": "dark",
            "language": "fr",
            "read.receipts.always": "false"
          }
        }
      ]
    },
    "c2"]
  ]
}
....

==== Partial Settings update

Based on the previous request Settings/set, we want to do some partial updates:

....
{
  "using": ["urn:ietf:params:jmap:core", "com:linagora:params:jmap:settings"],
  "methodCalls": [
    [
      "Settings/set",
      {
        "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
        "update": {
          "singleton": {
            "settings/timezone": "UTC+1",
            "settings/appearance.theme": "light"
          }
        }
      },
      "c1"
    ],
    [
      "Settings/get",
      {
        "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
        "ids": null
      },
      "c2"
    ]
  ]
}
....

Will return:

....
{
  "sessionState": "abcdefghij",
  "methodResponses": [
    ["Settings/set",
    {
      "accountId": "123",
      "newState": "1",
      "updated": {"singleton":{}}
    },
    "c1"],
    ["Settings/get",
    {
      "accountId": "123",
      "notFound": [],
      "state": "1",
      "list": [
        {
          "id": "singleton",
          "settings": {
            "tdrive.attachment.import.enabled": "true",
            "firebase.enabled": "true",
            "timezone": "UTC+1",
            "appearance.theme": "light",
            "language": "fr",
            "read.receipts.always": "false"
          }
        }
      ]
    },
    "c2"]
  ]
}
....

== Documented settings keys

=== Firebase push enable option
Some users are OK with their data being flowed through Firebase Cloud Messaging, while others are not OK.

This setting entry allows users to enable/disable TMail pushing their data via Firebase Cloud Messaging.

Setting key: `firebase.enabled`.
Optional. Boolean as String. Default value to `true`.

Please pay attention that if an account owner disables the Firebase push, his data change would not be transited via FCM to delegatees.

=== Trash cleanup enable
Setting key: `trash.cleanup.enabled`
Setting value: One in these values (`true`, `false`). Optional. Default value to `false`.

This setting is used to enable/disable the trash cleanup function

=== Trash cleanup period
Setting key: `trash.cleanup.period`
Setting value: One in these values (`weekly`, `monthly`). Optional. Default value to `monthly`.

This setting is used to determine if a message in trash should be keep or deleted. For example, if the value is `weekly`, any messages that exist for more than a week would be deleted.

=== Spam cleanup enable

Setting key: `spam.cleanup.enabled`
Optional. Boolean as String. Default value to `false`.

This setting is used to enable/disable the spam cleanup function.

=== Spam cleanup period

Setting key: `spam.cleanup.period`
Optional. One in these values (`weekly`, `monthly`). Defaults to `monthly`.

This setting is used to determine if a message in spam should be kept or deleted.
For example, if the value is `weekly`, any messages that exists for more than a week will be deleted when running the spam cleanup task.

=== Inbox archival settings
The following settings are related to the Inbox archival automation task that allows old messages in user's INBOX to be archived.

==== inbox.archival.enabled
This setting allows TMail backend to automatically archive old messages of Inbox to Archive mailbox(es) for the user.

Optional. Boolean as String. Default value to `false`.

==== inbox.archival.period
This setting specifies how old that a message should be archived.

Optional. String. One in these values (`monthly`, `yearly`). Default value to `monthly`.

==== inbox.archival.format
This setting specifies the structure of Archive mailboxes.

Optional. String. One in these values (`single`, `monthly`, `yearly`). Default value to `single`.

- `single`: Mails are archived under the `Archive` mailbox.
- `yearly`: Mails are archived in sub-mailboxes representing years, eg `Archive.2021`, `Archive.2022`...
- `monthly`: Mails are archived in nested sub-mailboxes representing months and years, eg `Archive.2021.1`, `Archive.2021.12`...

=== Mail label classification
Setting key: `ai.label-categorization.enabled`.
Setting value: Boolean (`true`, `false`). Optional. Default value to `true`.

This setting is used to enable/disable the needs-action classification on mails using AI.
