server:
  port: ${APISIX_PLUGIN_SERVER_PORT:8081}
logging:
  level:
    RevokedTokenPlugin: debug
    RewriteXUserPlugin: debug
    root: info
  pattern:
    console: "%clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"

cache.config:
  expired: 3600
  capacity: 1000
socket:
  file: ${APISIX_LISTEN_ADDRESS:unix:/tmp/runner.sock}

redis:
  url: ${REDIS_URL:localhost:6379}
  password: ${REDIS_PASSWORD:}
  topology: ${REDIS_TOPOLOGY:standalone}
  ignoreErrors: ${REDIS_IGNORE_ERRORS:true}
  timeout: ${REDIS_TIMEOUT:5000}

app:
  rewrite_xuser.userinfo_field: ${APP_REWRITE_XUSER_USERINFO_FIELD:sub}  # The X-Userinfo value of different OIDC providers is different. This property for extract exactly X-User value