= AIBotMailet

`AIBotMailet` is a mailet designed to automatically reply to emails sent to a specific recipient (e.g., gpt@linagora.com). It uses the OpenAI API by default but can be configured to use any LLM API supported by https://github.com/langchain4j/[langchain4j].

== Configuration Example

[source,xml]
----
<mailet match="com.linagora.tmail.mailet.RecipientsContain=gpt@linagora.com" class="com.linagora.tmail.mailet.AIBotMailet">
    <apiKey>demo</apiKey>
    <gptAddress>gpt@tmail.com</gptAddress>
    <model>openai,gpt-4o-mini</model>
</mailet>
----

=== Parameters

The mailet configuration requires the following parameters:

* `apiKey`: The API key for accessing the LLM API service.
* `gptAddress`: The email address used to send replies generated by the LLM model.
* `baseURL`: The base URL of the LLM's API.
* `model`: This is LLM model to be used, formatted as {llm_api},{llm_model}. Both values are optional, and if not provided, the default will be `openai,gpt-3.5-turbo` as configured by Langchain4j. For testing purposes, you can use the model `openai,gpt-4o-mini` with the demo API key.
