pipeline {
    agent any
    
    stages {
        stage('Git checkout') {
            steps {
                git 'https://github.com/linagora/tmail-backend'
                sh 'git submodule init'
                sh 'git submodule update'
            }
        }
        stage('Compile') {
            steps {
                sh 'mvn clean install -Dmaven.javadoc.skip=true -DskipTests -T1C'
            }
        }
        stage('Test') {
            steps {
                dir("tmail-backend") {
                    sh 'mvn -B surefire:test'
                }
            }
        }
    }
}