version: '3'

networks:
  emaily:
    driver: bridge

services:
  james:
    depends_on:
      - elasticsearch
      - cassandra
      - tika
      - rabbitmq
      - s3
    image: linagora/tmail-backend-distributed-esv6
    container_name: james
    hostname: james.local
    ports:
      - "80:80"
      - "25:25"
      - "110:110"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "8000:8000"
    networks:
      - emaily
    volumes:
      - [/PATH/TO/RSA_PUBLICKEY ]:/root/conf/jwt_publickey # Replace with absolute path to your RSA public key
      - [/PATH/TO/RSA_PRIVATEKEY]:/root/conf/jwt_privatekey # Replace with absolute path to your RSA private key
      # Key generation:
      # openssl genrsa -out jwt_privatekey 4096
      # openssl rsa -in jwt_privatekey -pubout > jwt_publickey

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - discovery.type=single-node
    networks:
      - emaily

  cassandra:
    image: cassandra:3.11.10
    ports:
      - "9042:9042"
    networks:
      - emaily

  tika:
    image: apache/tika:1.24
    networks:
      - emaily

  rabbitmq:
    image: rabbitmq:3.8.17-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - emaily

  s3:
    image: zenko/cloudserver:8.2.6
    container_name: s3.docker.test
    environment:
      - SCALITY_ACCESS_KEY_ID=accessKey1
      - SCALITY_SECRET_ACCESS_KEY=secretKey1
      - S3BACKEND=mem
      - LOG_LEVEL=trace
      - REMOTE_MANAGEMENT_DISABLE=1
    networks:
      - emaily

