# Use this configuration for local testing / docs develop.
site:
  title: Team-mail Documentation
  start_page: team-mail-site::index.adoc
content:
  sources:
    - url: ./../
      branches: HEAD
      start_path: docs
    - url: ./..
      branches: HEAD
      start_path: james-project/server/apps/distributed-app/docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
  supplemental_files: ./ui-overrides
runtime:
  fetch: true