#!/bin/bash

unset JAVA_TOOL_OPTIONS
java -cp "/root/extensions-jars/*:/root/libs/*:/root/resources:/root/classes" \
-Dlogback.configurationFile=/root/conf/logback-cli.xml \
org.apache.james.cli.ServerCmd "$@"