name: Create PR from Fork to Upstream

on:
  schedule:
    - cron: '*/5 * * * *'  # Chạy mỗi 5 phút
  push:
    branches:
      - master  # Hoặc nhánh mà bạn muốn theo dõi

jobs:
  createPullRequest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Lấy cả submodule

      # Cập nhật submodule hoặc các thay đổi khác
      - name: Update submodule
        run: |
          git config user.name 'Tung TV-bot'
          git config user.email 'vttran@linagora.com'
          date +%s > report.txt
          git add -A
          git commit -m "Update submodule james-project" || echo "No changes to commit"

      # Tạo pull request từ fork tới upstream
      - name: Create Pull Request to Upstream
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT_TOKEN }}  # Dùng token để có quyền tạo PR
          base: master  # Nhánh của repo tổ chức (linagora/tmail-backend)
          branch: upgradeSha1  # Nhánh của repo cá nhân
          delete-branch: true
          title: "Update James submodule to latest version"
          body: "This pull request updates the submodule to the latest version."
          commit-message: "Update James submodule to latest version"
#          push-to-fork: linagora/tmail-backend  # Fork của repo tổ chức
