name: Create PR from Fork to Upstream

on:
  schedule:
    - cron: '*/5 * * * *'  # Chạy mỗi 5 phút
  workflow_dispatch:

jobs:
  createPullRequest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Check if submodule is updated
        id: check-submodule
        run: |
          git submodule update --remote -- james-project
          if [ "$(git diff --submodule=log)" != "" ]; then
            echo "Submodule has changes"
            echo "changed=yes" >> $GITHUB_OUTPUT
          else
            echo "No changes in submodule"
            echo "changed=no" >> $GITHUB_OUTPUT
          fi
      - name: Commit and push if submodule updated
        if: ${{ steps.check-submodule.outputs.changed == 'yes' }}
        run: |
          git config user.name 'TungTV-auto'
          git config user.email 'vttran@linagora.com'
          git checkout -b upgradeSha2
          git add .
          git commit -m "Update submodule james-project"

      # Tạo pull request từ fork tới upstream
      - name: Create Pull Request to Upstream
        uses: peter-evans/create-pull-request@v7
        with:
#          token: ${{ secrets.PAT_TOKEN }}
          base: master
          branch: upgradeSha1
          delete-branch: true
          title: "Update James submodule to latest version"
          body: "This pull request updates the submodule to the latest version."
          commit-message: "Update James SHA-1"
#          push-to-fork: linagora/tmail-backend  # Fork của repo tổ chức
