version: '3.8'

networks:
  emaily:
    driver: bridge

services:
  tmail-backend:
    image: linagora/tmail-backend-memory:latest
    container_name: tmail-backend
    hostname: tmail-backend.local
    ports:
      - "80:80"
      - "25:25"
      - "110:110"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "8000:8000"
    networks:
      - emaily
    volumes:
      - $PWD/jwt_publickey:/root/conf/jwt_publickey
      - $PWD/jwt_privatekey:/root/conf/jwt_privatekey
      - $PWD/src/main/conf/smtpserver.xml:/root/conf/smtpserver.xml
      - $PWD/src/main/conf/imapserver.xml:/root/conf/imapserver.xml
      - ./target/imap-extensions-1.0.0-SNAPSHOT-jar-with-dependencies.jar:/root/extensions-jars/imap-extensions.jar
    healthcheck:
      test: [ "CMD-SHELL", "wget -S --spider http://localhost:8000/domains || exit 1" ]
      interval: 5s
      timeout: 10s
      retries: 3

  provision-sample-data:
    image: curlimages/curl:latest
    container_name: create-users
    depends_on:
      tmail-backend:
        condition: service_healthy
    volumes:
      - ./script_create_sample_data_for_docker_compose.sh:/usr/local/bin/provision.sh
    entrypoint: ["sh", "/usr/local/bin/provision.sh"]
    networks:
      - emaily
